<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>STAT-462 Lab book</title>
  <meta name="description" content="Lab Book for STAT-462 2021" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="STAT-462 Lab book" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Lab Book for STAT-462 2021" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="STAT-462 Lab book" />
  
  <meta name="twitter:description" content="Lab Book for STAT-462 2021" />
  

<meta name="author" content="Helen Greatrex" />


<meta name="date" content="2021-03-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  

<link rel="next" href="lab-1.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Penn State STAT-462 2021</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Tutorials</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#S.Tutorial.1A"><i class="fa fa-check"></i><b>1.1</b> Tutorial 1A: Installing R and R-studio</a><ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#S.Tutorial.1A.1"><i class="fa fa-check"></i><b>1.1.1</b> Open R-studio</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#S.Tutorial.1A.2"><i class="fa fa-check"></i><b>1.1.2</b> Change a few settings</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#S.Tutorial.1B"><i class="fa fa-check"></i><b>1.2</b> Tutorial 1B: Creating and loading R projects</a><ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#S.Tutorial.1B.1"><i class="fa fa-check"></i><b>1.2.1</b> What are projects?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#S.Tutorial.1C"><i class="fa fa-check"></i><b>1.3</b> Tutorial 1C: R coding basics</a><ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#S.Tutorial.1C.1"><i class="fa fa-check"></i><b>1.3.1</b> Using R as a calculator</a></li>
<li class="chapter" data-level="1.3.2" data-path="index.html"><a href="index.html#S.Tutorial.1C.2"><i class="fa fa-check"></i><b>1.3.2</b> Adding text</a></li>
<li class="chapter" data-level="1.3.3" data-path="index.html"><a href="index.html#S.Tutorial.1C.3"><i class="fa fa-check"></i><b>1.3.3</b> Comparisons</a></li>
<li class="chapter" data-level="1.3.4" data-path="index.html"><a href="index.html#S.Tutorial.1C.4"><i class="fa fa-check"></i><b>1.3.4</b> What if I press Enter too soon?</a></li>
<li class="chapter" data-level="1.3.5" data-path="index.html"><a href="index.html#S.Tutorial.1C.5"><i class="fa fa-check"></i><b>1.3.5</b> Variables and assignment</a></li>
<li class="chapter" data-level="1.3.6" data-path="index.html"><a href="index.html#S.Tutorial.1C.7"><i class="fa fa-check"></i><b>1.3.6</b> Functions</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#S.Tutorial.1D"><i class="fa fa-check"></i><b>1.4</b> Tutorial 1D: Packages</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#S.Tutorial.1E"><i class="fa fa-check"></i><b>1.5</b> Tutorial 1E: R Markdown basics</a><ul>
<li class="chapter" data-level="1.5.1" data-path="index.html"><a href="index.html#S.Tutorial.1E.1"><i class="fa fa-check"></i><b>1.5.1</b> What is R-markdown?</a></li>
<li class="chapter" data-level="1.5.2" data-path="index.html"><a href="index.html#S.Tutorial.1E.2"><i class="fa fa-check"></i><b>1.5.2</b> Creating a markdown document</a></li>
<li class="chapter" data-level="1.5.3" data-path="index.html"><a href="index.html#S.Tutorial.1E.3"><i class="fa fa-check"></i><b>1.5.3</b> “Friendly text”</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#S.Tutorial.2A"><i class="fa fa-check"></i><b>1.6</b> Tutorial 2A: Getting help in R</a><ul>
<li class="chapter" data-level="1.6.1" data-path="index.html"><a href="index.html#S.Tutorial.2A.1"><i class="fa fa-check"></i><b>1.6.1</b> Help on a specific command</a></li>
<li class="chapter" data-level="1.6.2" data-path="index.html"><a href="index.html#S.Tutorial.2A.2"><i class="fa fa-check"></i><b>1.6.2</b> Finding a command name</a></li>
<li class="chapter" data-level="1.6.3" data-path="index.html"><a href="index.html#S.Tutorial.2A.3"><i class="fa fa-check"></i><b>1.6.3</b> Asking the internet:</a></li>
<li class="chapter" data-level="1.6.4" data-path="index.html"><a href="index.html#S.Tutorial.2A.4"><i class="fa fa-check"></i><b>1.6.4</b> General help &amp; cheatsheets</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#S.Tutorial.2B"><i class="fa fa-check"></i><b>1.7</b> Tutorial 2B: Markdown formats</a><ul>
<li class="chapter" data-level="1.7.1" data-path="index.html"><a href="index.html#S.Tutorial.2B.1"><i class="fa fa-check"></i><b>1.7.1</b> Editing YAML code</a></li>
<li class="chapter" data-level="1.7.2" data-path="index.html"><a href="index.html#S.Tutorial.2B.2"><i class="fa fa-check"></i><b>1.7.2</b> Text formats</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#S.Tutorial.2C"><i class="fa fa-check"></i><b>1.8</b> Tutorial 2C: Selecting &amp; summarising data</a><ul>
<li class="chapter" data-level="1.8.1" data-path="index.html"><a href="index.html#S.Tutorial.2C.1"><i class="fa fa-check"></i><b>1.8.1</b> Data.frame introduction</a></li>
<li class="chapter" data-level="1.8.2" data-path="index.html"><a href="index.html#S.Tutorial.2C.2"><i class="fa fa-check"></i><b>1.8.2</b> Selecting individual values</a></li>
<li class="chapter" data-level="1.8.3" data-path="index.html"><a href="index.html#S.Tutorial.2C.3"><i class="fa fa-check"></i><b>1.8.3</b> Selecting a single column</a></li>
<li class="chapter" data-level="1.8.4" data-path="index.html"><a href="index.html#S.Tutorial.2C.4"><i class="fa fa-check"></i><b>1.8.4</b> Selecting mulitple columns</a></li>
<li class="chapter" data-level="1.8.5" data-path="index.html"><a href="index.html#S.Tutorial.2C.5"><i class="fa fa-check"></i><b>1.8.5</b> Selecting subsets of rows/observations</a></li>
<li class="chapter" data-level="1.8.6" data-path="index.html"><a href="index.html#S.Tutorial.2C.6"><i class="fa fa-check"></i><b>1.8.6</b> Looking at summary tables</a></li>
<li class="chapter" data-level="1.8.7" data-path="index.html"><a href="index.html#S.Tutorial.2C.7"><i class="fa fa-check"></i><b>1.8.7</b> Basic plots (one variable)</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#S.Tutorial.2D"><i class="fa fa-check"></i><b>1.9</b> Tutorial 2D: Distributions and tests</a><ul>
<li class="chapter" data-level="1.9.1" data-path="index.html"><a href="index.html#S.Tutorial.2D.1"><i class="fa fa-check"></i><b>1.9.1</b> Normal distribution</a></li>
<li class="chapter" data-level="1.9.2" data-path="index.html"><a href="index.html#S.Tutorial.2D.2"><i class="fa fa-check"></i><b>1.9.2</b> Student’s t-distribution</a></li>
<li class="chapter" data-level="1.9.3" data-path="index.html"><a href="index.html#S.Tutorial.2D.3"><i class="fa fa-check"></i><b>1.9.3</b> Wilks Shapiro test for normality</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="index.html"><a href="index.html#S.Tutorial.3A"><i class="fa fa-check"></i><b>1.10</b> Tutorial 3A - Editing code chunks</a></li>
<li class="chapter" data-level="1.11" data-path="index.html"><a href="index.html#S.Tutorial.3B"><i class="fa fa-check"></i><b>1.11</b> Tutorial 3B - Regression Models</a><ul>
<li class="chapter" data-level="1.11.1" data-path="index.html"><a href="index.html#S.Tutorial.3B.1"><i class="fa fa-check"></i><b>1.11.1</b> “Standard” regression output</a></li>
<li class="chapter" data-level="1.11.2" data-path="index.html"><a href="index.html#S.Tutorial.3B.2"><i class="fa fa-check"></i><b>1.11.2</b> “Fancy” OLSRR regression output</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="index.html"><a href="index.html#S.Tutorial.4A"><i class="fa fa-check"></i><b>1.12</b> Tutorial 4A: Plotting in ggplot2</a></li>
<li class="chapter" data-level="1.13" data-path="index.html"><a href="index.html#S.Tutorial.4B"><i class="fa fa-check"></i><b>1.13</b> Tutorial 4B: Identifying/removing outliers</a></li>
<li class="chapter" data-level="1.14" data-path="index.html"><a href="index.html#S.Tutorial.4C"><i class="fa fa-check"></i><b>1.14</b> Tutorial 4C Writing equations in R-Studio</a><ul>
<li class="chapter" data-level="1.14.1" data-path="index.html"><a href="index.html#S.Tutorial.4C.1"><i class="fa fa-check"></i><b>1.14.1</b> In Markdown</a></li>
<li class="chapter" data-level="1.14.2" data-path="index.html"><a href="index.html#S.Tutorial.4C.2"><i class="fa fa-check"></i><b>1.14.2</b> Using Equatiomatic</a></li>
</ul></li>
<li class="chapter" data-level="1.15" data-path="index.html"><a href="index.html#S.Tutorial.5A"><i class="fa fa-check"></i><b>1.15</b> Tutorial 5A ANOVA</a><ul>
<li class="chapter" data-level="1.15.1" data-path="index.html"><a href="index.html#S.Tutorial.5A.1"><i class="fa fa-check"></i><b>1.15.1</b> Base R</a></li>
<li class="chapter" data-level="1.15.2" data-path="index.html"><a href="index.html#S.Tutorial.5A.2"><i class="fa fa-check"></i><b>1.15.2</b> Using OLSRR</a></li>
</ul></li>
<li class="chapter" data-level="1.16" data-path="index.html"><a href="index.html#S.Tutorial.5B"><i class="fa fa-check"></i><b>1.16</b> Tutorial 5B Diagnostics part A</a><ul>
<li class="chapter" data-level="1.16.1" data-path="index.html"><a href="index.html#S.Tutorial.5B.1"><i class="fa fa-check"></i><b>1.16.1</b> Residual plots</a></li>
<li class="chapter" data-level="1.16.2" data-path="index.html"><a href="index.html#S.Tutorial.5B.2"><i class="fa fa-check"></i><b>1.16.2</b> Checking Linearity</a></li>
<li class="chapter" data-level="1.16.3" data-path="index.html"><a href="index.html#S.Tutorial.5B.3"><i class="fa fa-check"></i><b>1.16.3</b> Checking Independence</a></li>
<li class="chapter" data-level="1.16.4" data-path="index.html"><a href="index.html#S.Tutorial.5B.4"><i class="fa fa-check"></i><b>1.16.4</b> Checking Normality</a></li>
<li class="chapter" data-level="1.16.5" data-path="index.html"><a href="index.html#S.Tutorial.5B.5"><i class="fa fa-check"></i><b>1.16.5</b> Checking Equal Variance/homoskadisity</a></li>
</ul></li>
<li class="chapter" data-level="1.17" data-path="index.html"><a href="index.html#S.Tutorial.5C"><i class="fa fa-check"></i><b>1.17</b> Tutorial 5C Confidence and Prediction Intervals</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="lab-1.html"><a href="lab-1.html"><i class="fa fa-check"></i><b>2</b> Lab 1</a><ul>
<li class="chapter" data-level="2.1" data-path="lab-1.html"><a href="lab-1.html#getting-started"><i class="fa fa-check"></i><b>2.1</b> Getting started</a><ul>
<li class="chapter" data-level="2.1.1" data-path="lab-1.html"><a href="lab-1.html#why-is-this-class-in-r"><i class="fa fa-check"></i><b>2.1.1</b> Why is this class in R?</a></li>
<li class="chapter" data-level="2.1.2" data-path="lab-1.html"><a href="lab-1.html#installing-r-and-r-studio"><i class="fa fa-check"></i><b>2.1.2</b> Installing R and R-studio</a></li>
<li class="chapter" data-level="2.1.3" data-path="lab-1.html"><a href="lab-1.html#open-r-studio"><i class="fa fa-check"></i><b>2.1.3</b> Open R-studio</a></li>
<li class="chapter" data-level="2.1.4" data-path="lab-1.html"><a href="lab-1.html#change-a-few-settings"><i class="fa fa-check"></i><b>2.1.4</b> Change a few settings</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="lab-1.html"><a href="lab-1.html#lab-challenge-1"><i class="fa fa-check"></i><b>2.2</b> Lab challenge 1</a><ul>
<li class="chapter" data-level="2.2.1" data-path="lab-1.html"><a href="lab-1.html#what-are-projects"><i class="fa fa-check"></i><b>2.2.1</b> What are projects?</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="lab-1.html"><a href="lab-1.html#r-coding-basics"><i class="fa fa-check"></i><b>2.3</b> R coding basics</a><ul>
<li class="chapter" data-level="2.3.1" data-path="lab-1.html"><a href="lab-1.html#variables-and-assignment"><i class="fa fa-check"></i><b>2.3.1</b> Variables and assignment</a></li>
<li class="chapter" data-level="2.3.2" data-path="lab-1.html"><a href="lab-1.html#functions"><i class="fa fa-check"></i><b>2.3.2</b> Functions</a></li>
<li class="chapter" data-level="2.3.3" data-path="lab-1.html"><a href="lab-1.html#packages"><i class="fa fa-check"></i><b>2.3.3</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="lab-1.html"><a href="lab-1.html#lab-challenge-2"><i class="fa fa-check"></i><b>2.4</b> Lab Challenge 2</a></li>
<li class="chapter" data-level="2.5" data-path="lab-1.html"><a href="lab-1.html#markdown-exploratory-analysis"><i class="fa fa-check"></i><b>2.5</b> Markdown &amp; Exploratory Analysis</a><ul>
<li class="chapter" data-level="2.5.1" data-path="lab-1.html"><a href="lab-1.html#what-is-r-markdown"><i class="fa fa-check"></i><b>2.5.1</b> What is R-markdown?</a></li>
<li class="chapter" data-level="2.5.2" data-path="lab-1.html"><a href="lab-1.html#creating-a-markdown-document"><i class="fa fa-check"></i><b>2.5.2</b> Creating a markdown document</a></li>
<li class="chapter" data-level="2.5.3" data-path="lab-1.html"><a href="lab-1.html#friend"><i class="fa fa-check"></i><b>2.5.3</b> “Friendly text”</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="lab-1.html"><a href="lab-1.html#lab-challenge-3"><i class="fa fa-check"></i><b>2.6</b> Lab Challenge 3</a></li>
<li class="chapter" data-level="2.7" data-path="lab-1.html"><a href="lab-1.html#submitting-lab-1-section.l1.7"><i class="fa fa-check"></i><b>2.7</b> Submitting Lab 1 {Section.L1.7}</a><ul>
<li class="chapter" data-level="2.7.1" data-path="lab-1.html"><a href="lab-1.html#lab-1-submission-check"><i class="fa fa-check"></i><b>2.7.1</b> Lab 1 submission check</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="lab-2.html"><a href="lab-2.html"><i class="fa fa-check"></i><b>3</b> Lab 2</a><ul>
<li class="chapter" data-level="3.1" data-path="lab-2.html"><a href="lab-2.html#general-information"><i class="fa fa-check"></i><b>3.1</b> General information</a></li>
<li class="chapter" data-level="3.2" data-path="lab-2.html"><a href="lab-2.html#tutorials"><i class="fa fa-check"></i><b>3.2</b> Tutorials</a></li>
<li class="chapter" data-level="3.3" data-path="lab-2.html"><a href="lab-2.html#setting-up-your-code"><i class="fa fa-check"></i><b>3.3</b> Setting up your code</a></li>
<li class="chapter" data-level="3.4" data-path="lab-2.html"><a href="lab-2.html#markdown-formatting-and-yaml"><i class="fa fa-check"></i><b>3.4</b> Markdown formatting and YAML</a></li>
<li class="chapter" data-level="3.5" data-path="lab-2.html"><a href="lab-2.html#confidence-intervals"><i class="fa fa-check"></i><b>3.5</b> Confidence intervals</a></li>
<li class="chapter" data-level="3.6" data-path="lab-2.html"><a href="lab-2.html#hypothesis-testing"><i class="fa fa-check"></i><b>3.6</b> Hypothesis testing</a></li>
<li class="chapter" data-level="3.7" data-path="lab-2.html"><a href="lab-2.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>3.7</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="3.8" data-path="lab-2.html"><a href="lab-2.html#submitting-lab-2"><i class="fa fa-check"></i><b>3.8</b> Submitting Lab 2</a><ul>
<li class="chapter" data-level="3.8.1" data-path="lab-2.html"><a href="lab-2.html#lab-2-submission-check"><i class="fa fa-check"></i><b>3.8.1</b> Lab 2 submission check</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lab-3.html"><a href="lab-3.html"><i class="fa fa-check"></i><b>4</b> Lab 3</a><ul>
<li class="chapter" data-level="4.1" data-path="lab-3.html"><a href="lab-3.html#lab-3-general-information"><i class="fa fa-check"></i><b>4.1</b> Lab 3 General information</a></li>
<li class="chapter" data-level="4.2" data-path="lab-3.html"><a href="lab-3.html#installing-new-packages"><i class="fa fa-check"></i><b>4.2</b> Installing new packages</a></li>
<li class="chapter" data-level="4.3" data-path="lab-3.html"><a href="lab-3.html#lab-3-setup-markdown"><i class="fa fa-check"></i><b>4.3</b> Lab 3 Setup &amp; Markdown</a></li>
<li class="chapter" data-level="4.4" data-path="lab-3.html"><a href="lab-3.html#regression-basics"><i class="fa fa-check"></i><b>4.4</b> Regression basics</a></li>
<li class="chapter" data-level="4.5" data-path="lab-3.html"><a href="lab-3.html#taiwan-housing-challenge."><i class="fa fa-check"></i><b>4.5</b> Taiwan housing challenge.</a></li>
<li class="chapter" data-level="4.6" data-path="lab-3.html"><a href="lab-3.html#submitting-lab-3"><i class="fa fa-check"></i><b>4.6</b> Submitting Lab 3</a><ul>
<li class="chapter" data-level="4.6.1" data-path="lab-3.html"><a href="lab-3.html#lab-3-submission-check"><i class="fa fa-check"></i><b>4.6.1</b> Lab 3 submission check</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="lab-4.html"><a href="lab-4.html"><i class="fa fa-check"></i><b>5</b> Lab 4</a><ul>
<li class="chapter" data-level="5.1" data-path="lab-4.html"><a href="lab-4.html#lab-4-general-information"><i class="fa fa-check"></i><b>5.1</b> Lab 4 General information</a></li>
<li class="chapter" data-level="5.2" data-path="lab-4.html"><a href="lab-4.html#lab-4-setup-markdown"><i class="fa fa-check"></i><b>5.2</b> Lab 4 Setup &amp; Markdown</a></li>
<li class="chapter" data-level="5.3" data-path="lab-4.html"><a href="lab-4.html#public-safety-spending"><i class="fa fa-check"></i><b>5.3</b> Public safety spending</a><ul>
<li class="chapter" data-level="" data-path="lab-4.html"><a href="lab-4.html#checking-folder-names"><i class="fa fa-check"></i>Checking folder names</a></li>
<li class="chapter" data-level="" data-path="lab-4.html"><a href="lab-4.html#reading-in-the-data"><i class="fa fa-check"></i>Reading in the data</a></li>
<li class="chapter" data-level="" data-path="lab-4.html"><a href="lab-4.html#analysis"><i class="fa fa-check"></i>Analysis</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="lab-4.html"><a href="lab-4.html#submitting-lab-4"><i class="fa fa-check"></i><b>5.4</b> Submitting Lab 4</a><ul>
<li class="chapter" data-level="5.4.1" data-path="lab-4.html"><a href="lab-4.html#lab-4-submission-check"><i class="fa fa-check"></i><b>5.4.1</b> Lab 4 submission check</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="lab-5.html"><a href="lab-5.html"><i class="fa fa-check"></i><b>6</b> Lab 5</a><ul>
<li class="chapter" data-level="6.1" data-path="lab-5.html"><a href="lab-5.html#lab-5-general-information"><i class="fa fa-check"></i><b>6.1</b> Lab 5 General information</a></li>
<li class="chapter" data-level="6.2" data-path="lab-5.html"><a href="lab-5.html#lab-5-setup-markdown"><i class="fa fa-check"></i><b>6.2</b> Lab 5 Setup &amp; Markdown</a></li>
<li class="chapter" data-level="6.3" data-path="lab-5.html"><a href="lab-5.html#submitting-lab-5"><i class="fa fa-check"></i><b>6.3</b> Submitting Lab 5</a><ul>
<li class="chapter" data-level="6.3.1" data-path="lab-5.html"><a href="lab-5.html#lab-5-submission-check"><i class="fa fa-check"></i><b>6.3.1</b> Lab 5 submission check</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STAT-462 Lab book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">STAT-462 Lab book</h1>
<p class="author"><em>Helen Greatrex</em></p>
<p class="date"><em>2021-03-04</em></p>
</div>
<div id="S.Tutorial" class="section level1">
<h1><span class="header-section-number">Chapter 1</span> Tutorials</h1>
<div id="S.Tutorial.1A" class="section level2">
<h2><span class="header-section-number">1.1</span> Tutorial 1A: Installing R and R-studio</h2>
<p>In this class, we would like you to download and install BOTH R and R-Studio onto your own computers. You should have already completed this step for Homework 1. If you have not, see instructions here: <a href="https://psu.instructure.com/courses/2115020/assignments/12682456" class="uri">https://psu.instructure.com/courses/2115020/assignments/12682456</a></p>
<p>FOR WINDOWS USERS. Sometimes R asks you to download something called RTools. You can do so here: <a href="https://cran.r-project.org/bin/windows/Rtools/" class="uri">https://cran.r-project.org/bin/windows/Rtools/</a> Follow the instructions closely and ask if you need support.</p>
<div id="S.Tutorial.1A.1" class="section level3">
<h3><span class="header-section-number">1.1.1</span> Open R-studio</h3>
<div class="figure"><span id="fig:rrstudiot"></span>
<img src="images/Fig_01_01RRstudio.png" alt="Icons of the R program and R-studio" width="1048" />
<p class="caption">
Figure 1.1: Icons of the R program and R-studio
</p>
</div>
<p><strong>Open R-studio</strong> (NOT R!). You should be greeted by three panels:</p>
<ul>
<li>The interactive R console (entire left)</li>
<li>Environment/History (tabbed in upper right)</li>
<li>Files/Plots/Packages/Help/Viewer (tabbed in lower right)</li>
</ul>
<p>If you click on the View/Panes/Pane Layout menu item, you can move these quadrants around. I tend to like the console to be top left and scripts to be top right, with the plots and environment on the bottom - but this is totally personal choice.</p>
<div class="figure"><span id="fig:basicStudiot"></span>
<img src="images/Fig_01_02Rstudio.png" alt="The basic R-studio screen when you log on" width="889" />
<p class="caption">
Figure 1.2: The basic R-studio screen when you log on
</p>
</div>
<p>If you wish to learn more about what these windows do, have a look at this resource, from the Pirates Guide to R: <a href="https://bookdown.org/ndphillips/YaRrr/the-four-rstudio-windows.html" class="uri">https://bookdown.org/ndphillips/YaRrr/the-four-rstudio-windows.html</a></p>
<p><strong>If you have used R before, you might see that there are variables and plots etc already loaded</strong>. It is always good to clear these before you start a new analysis. To do this, click the little broom symbol in your environment tab.</p>
</div>
<div id="S.Tutorial.1A.2" class="section level3">
<h3><span class="header-section-number">1.1.2</span> Change a few settings</h3>
<p>R-studio wants to be helpful and will try to re-load exactly where you were in a project when you log back in. This can get really confusing, so we are going to turn this off.</p>
<p>ON A MAC: Click on the R-studio menu button on the top left of the screen, then click Preferences.</p>
<p>ON A PC: Click on Tools-&gt; Global Options -&gt; Preferences</p>
<p>Now:</p>
<ul>
<li>UNCLICK “Restore most recently opened project at startup”</li>
<li>Set “Save workspace to .RData on” exit to Never</li>
</ul>
</div>
</div>
<div id="S.Tutorial.1B" class="section level2">
<h2><span class="header-section-number">1.2</span> Tutorial 1B: Creating and loading R projects</h2>
<div id="S.Tutorial.1B.1" class="section level3">
<h3><span class="header-section-number">1.2.1</span> What are projects?</h3>
<p><a href="https://www.linkedin.com/learning/learning-the-r-tidyverse/why-should-you-use-projects-in-rstudio?u=76811570" title="Why use R Projects"><img src="images/Fig_01_03VIDEO_Projects.png" alt="Rproject2" /></a></p>
<p>One of the most useful new features in RStudio are R-Projects. We are going to use R-projects to store our lab data in. An R project is a place to store all your commands, data and output in the same place.</p>
<p>Before R projects, we had to worry about where on your computer your data was saved in. Now, we can force R-Studio to immediately look inside your lab folder - making life much easier.</p>
<p>Equally, projects allow you to have multiple versions of R-studio open. This is useful because say you have Lab-2 open, but want to re-open Lab-1 to check some code, clicking the “Lab 1 project file” will load a whole new version of R with Lab 1 ready to edit.</p>
<p>It is <strong><em>really</em></strong> important that you stay organized in this course, for example making sure you know where you put your data and your labs.</p>
<p><strong>To encourage this, choose a place that makes sense on your computer, create a folder called STAT-462. can either do this outside R studio in your file explorer, or inside the “Files tab” in R studio. You should store all your 462 labs inside this folder</strong></p>
<p>Now we will create our first project (also see the pic):</p>
<ul>
<li>open R-Studio and click <code>New Project</code>,</li>
<li>then click “new directory”</li>
<li>then “new project”.</li>
<li>Name your project Lab 1, then browse to your newly created STAT-462 folder and press open.</li>
<li>Press OK and your project is created.
<ul>
<li>You will also see that a new sub-folder has been created in your STAT-462 folder called Lab 1</li>
<li>Inside that is your Project file. (with a .Rproj extension)</li>
</ul></li>
</ul>
<div class="figure"><span id="fig:projectt"></span>
<img src="images/Fig_01_04Project.png" alt="Instructions to create an R project" width="1889" />
<p class="caption">
Figure 1.3: Instructions to create an R project
</p>
</div>
<p>Your output should look something like this:</p>
<div class="figure"><span id="fig:finaloutt"></span>
<img src="images/Fig_01_05FinalOutput.png" alt="What you should see" width="1402" />
<p class="caption">
Figure 1.4: What you should see
</p>
</div>
<p>Equally, R should now be “looking” inside your Lab 1 folder, making it easier to find your data and output your results. Try typing this into the console (INCLUDING THE EMPTY PARANTHESES/BRACKETS) and see if it prints out the location of Lab 1 on your computer. If not, talk to an instructor.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="index.html#cb1-1"></a><span class="kw">getwd</span>()</span></code></pre></div>
<p>In the future, every time you want to work on Lab 1, rather than open R-studio directly, double click the R project file inside Lab 1 and you will get back to your work.</p>
<div id="if-youre-having-issues-at-this-point-or-havent-managed-to-get-to-this-step-stop-ask-an-instructor-for-help." class="section level5 unnumbered">
<h5>If you’re having issues at this point or haven’t managed to get to this step, STOP! Ask an instructor for help.</h5>
<p>Now you have opened your project, take a screenshot of your R-studio page. It should look like Figure <a href="index.html#fig:finaloutt">1.4</a>, e.g. with at least R version 4.0.3, with the Lab 1 project and the project stored in your STAT-462 folder.</p>
<ul>
<li>To take a screenshot on a mac, press Command-3. The screenshot will appear on your desktop</li>
<li>To take a screenshot on a PC, press Alt + PrtScn</li>
</ul>
<p>Rename the screenshot to your “username_Lab1_Fig1”(for example for me it will be hlg5155_Lab1_Fig1), then place it in your Lab 1 sub-folder inside STAT-462. This folder was created when you made the project.</p>
<p>You will need this later, so don’t skip this step.</p>
</div>
</div>
</div>
<div id="S.Tutorial.1C" class="section level2">
<h2><span class="header-section-number">1.3</span> Tutorial 1C: R coding basics</h2>
<p><a href="https://youtu.be/SWxoJqTqo08?t=41" title="R basics"><img src="images/Fig_01_07VIDEO_Basics.png" alt="Rbasics" /></a></p>
<p>So now we FINALLY get to do some R-coding. First things first, first watch the 5 min video above for some pointers. Will will also go through this below:</p>
<div id="S.Tutorial.1C.1" class="section level3">
<h3><span class="header-section-number">1.3.1</span> Using R as a calculator</h3>
<p>Remember that the aim of R is to type in commands to get your computer to analyse data. The console (see Figure <a href="index.html#fig:basicStudiot">1.2</a>) is a space where you can type in those commands and it will directly print out the answer. You’re essentially talking to the computer.</p>
<p>The little “&gt;” symbol in the console means that the computer is waiting for your command.</p>
<p>Let’s start by the simplest command possible. Try typing each of the following commands into your R console and pressing Enter as you work through this.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="index.html#cb2-1"></a><span class="dv">1</span><span class="op">+</span><span class="dv">1</span></span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>Note that spacing does not matter: <code>1+1</code> will generate the same answer as <code>1      +       1</code>.</p>
<p>When using R as a calculator, the order of operations is the same as you would have learned back in school, so use brackets to force a different order. For example,</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="index.html#cb4-1"></a><span class="dv">3</span> <span class="op">+</span><span class="st"> </span><span class="dv">5</span> <span class="op">*</span><span class="st"> </span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 13</code></pre>
<p>will give a different result to</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="index.html#cb6-1"></a>(<span class="dv">3</span> <span class="op">+</span><span class="st"> </span><span class="dv">5</span>) <span class="op">*</span><span class="st"> </span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 16</code></pre>
</div>
<div id="S.Tutorial.1C.2" class="section level3">
<h3><span class="header-section-number">1.3.2</span> Adding text</h3>
<p>Now for text. Can you say hello world?</p>
<div class="figure"><span id="fig:projectoutt"></span>
<img src="images/Fig_01_06HelloWorld.png" alt="Your screen after running the project" width="1063" />
<p class="caption">
Figure 1.5: Your screen after running the project
</p>
</div>
<p>Nope, there is an error! To make R understand text, it is important to use quote marks.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="index.html#cb8-1"></a><span class="kw">print</span>(<span class="st">&quot;Hello World&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Hello World&quot;</code></pre>
</div>
<div id="S.Tutorial.1C.3" class="section level3">
<h3><span class="header-section-number">1.3.3</span> Comparisons</h3>
<p>We can also do comparisons in R - using the special symbols TRUE or FALSE (no quote marks, they are special).</p>
<p>Here we are asking R whether 1 is equal to 1.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="index.html#cb10-1"></a><span class="co"># note two equals signs is read as &quot;is equal to&quot;</span></span>
<span id="cb10-2"><a href="index.html#cb10-2"></a><span class="dv">1</span> <span class="op">==</span><span class="st"> </span><span class="dv">1</span>  </span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>We could also have used</p>
<ul>
<li><code>!=</code> “Not equal to”</li>
<li><code>&lt;</code> “Less than”</li>
<li><code>&lt;=</code> "Less than or equal to`</li>
<li><code>&gt;</code> “Greater than”</li>
<li><code>&gt;=</code> “Greater than or equal to”</li>
</ul>
</div>
<div id="S.Tutorial.1C.4" class="section level3">
<h3><span class="header-section-number">1.3.4</span> What if I press Enter too soon?</h3>
<p>If you type in an incomplete command, R will wait for you to complete it. For example, if you type
<code>1 +</code> and press enter, R will know that you need to complete the command So it will move onto the next line but the <code>&gt;</code> will have changed into a <code>+</code>, which means its waiting for you to complete the command.</p>
<p><strong>If you want to cancel a command you can simply hit the “Esc” key or press the little stop symbol and R studio will reset.</strong></p>
<p>Pressing escape isn’t only useful for killing incomplete commands: you can also use it to tell R to stop running code (for example if it’s taking much longer than you expect), or to get rid of the code you’re currently writing.</p>
</div>
<div id="S.Tutorial.1C.5" class="section level3">
<h3><span class="header-section-number">1.3.5</span> Variables and assignment</h3>
<p>It’s great to be able to do maths easily on the screen, but really we want to be able to save our results, or load in data so we can run more complex commands. In R, we can give our data a name e.g. we save our data as a variable. So then, instead of typing the whole command, we can simply type the variable’s name and R will recall the answer.</p>
<p>The symbol to store data into a variable is using the assignment arrow <code>&lt;-</code>, which is made up of the left arrow and a dash. You can also use the equals sign, but it can cause complications later on. Try typing this command into the console:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="index.html#cb12-1"></a>x &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">/</span><span class="dv">50</span></span></code></pre></div>
<p>Notice that pressing enter did not print a value onto your screen as it did earlier. Instead, we stored it for later in something called a variable, with the name ‘x’.</p>
<p>So our variable <code>x</code> is now associated with the value 0.02, or 1/50. You can print a variable on screen by typing its name, no quotes, or by using the print command. Try printing out your variable.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="index.html#cb13-1"></a>x</span></code></pre></div>
<pre><code>## [1] 0.02</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="index.html#cb15-1"></a><span class="co"># or</span></span>
<span id="cb15-2"><a href="index.html#cb15-2"></a></span>
<span id="cb15-3"><a href="index.html#cb15-3"></a><span class="kw">print</span>(x)</span></code></pre></div>
<pre><code>## [1] 0.02</code></pre>
<p>Look for the Environment tab in one of the panes of RStudio, and you will see that ‘x’ and its value have appeared. This ‘x’ variable can be used in place of a number in any calculation that expects a number. Try typing</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="index.html#cb17-1"></a><span class="kw">log</span>(x)</span></code></pre></div>
<pre><code>## [1] -3.912023</code></pre>
<p>Notice also that variables can be reassigned:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="index.html#cb19-1"></a>x &lt;-<span class="st"> </span><span class="dv">100</span></span>
<span id="cb19-2"><a href="index.html#cb19-2"></a><span class="kw">print</span>(x)</span></code></pre></div>
<pre><code>## [1] 100</code></pre>
<p>x used to contain the value 0.025 and and now it has the value 100.</p>
<p><em>Note, the letter x isn’t special in any way, it’s just a variable name. You can replace it with any word you like as long as it contains no spaces and doesn’t begin with a number</em>. Different people use different conventions for long variable names, these include</p>
<ul>
<li>periods.between.words.1</li>
<li>underscores_between_words</li>
<li>camelCaseToSeparateWords</li>
</ul>
<p>What you use is up to you, but be consistent.</p>
<p>Finally, R IS CASE SENSITIVE. X and x are different variables!</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="index.html#cb21-1"></a>h &lt;-<span class="st"> </span><span class="dv">1</span></span>
<span id="cb21-2"><a href="index.html#cb21-2"></a>H &lt;-<span class="st"> </span><span class="dv">2</span></span>
<span id="cb21-3"><a href="index.html#cb21-3"></a></span>
<span id="cb21-4"><a href="index.html#cb21-4"></a>ans &lt;-<span class="st"> </span>h<span class="op">+</span>H</span>
<span id="cb21-5"><a href="index.html#cb21-5"></a><span class="kw">print</span>(ans)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div id="S.Tutorial.1C.6" class="section level4">
<h4><span class="header-section-number">1.3.5.1</span> Combining variables</h4>
<p>As I showed above, you can now use multiple variables together in more complex commands. For example, try these commands:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="index.html#cb23-1"></a><span class="co">#Take the variable x, add 1 then save it to a new variable called y</span></span>
<span id="cb23-2"><a href="index.html#cb23-2"></a>y &lt;-<span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="dv">1</span> </span>
<span id="cb23-3"><a href="index.html#cb23-3"></a><span class="co"># print the multiple of 2yx onto the screen</span></span>
<span id="cb23-4"><a href="index.html#cb23-4"></a>y</span></code></pre></div>
<pre><code>## [1] 101</code></pre>
<p>Now you can see that there are two variables in your environment tab, x and y. Where y is the sum of the contents of x plus 1.</p>
<p>The way R works is that first it looks for the commands on the right of the arrow. It runs all of them, calculates the result, then saves that result with the name on the left of the arrow. <strong>It does not save the command itself, just the answer.</strong> For example, in this case, R has no idea that y was created using a sum, it just knows that it is equal to the number 3.</p>
<p>You can even use this to change your original variable . Try typing the code below in a few times into the console and see what happens.</p>
<p><strong>A short cut to do this is to type the commands the first time, then use the up-arrow on your keyboard to cycle back through previous commands you have typed</strong></p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="index.html#cb25-1"></a>x &lt;-<span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="dv">1</span> <span class="co"># notice how RStudio updates its description of x in the environment tab</span></span>
<span id="cb25-2"><a href="index.html#cb25-2"></a>x          <span class="co"># print the contents of &quot;x&quot; onto the screen</span></span></code></pre></div>
<pre><code>## [1] 101</code></pre>
<p>Our variables don’t have to be numbers. They could refer to tables of data, or a spatial map, or any other complex thing. We will cover this more in future labs.</p>
</div>
</div>
<div id="S.Tutorial.1C.7" class="section level3">
<h3><span class="header-section-number">1.3.6</span> Functions</h3>
<p>A command is simply an action you can take - like pressing the square root button on a calculator, followed by the number you wish to take the square root of. A command is <em>always</em> followed by parentheses ( ), inside which you put your arguments.</p>
<p>The power of R lies in its many thousands of these built in commands, or <em>functions</em>. In fact, we have already come across one - the print command. Some more examples include:</p>
<ul>
<li><code>plot(x=1:10,y=1:10)</code>
<ul>
<li>This will plot the numbers 1 to 10 against 1 to 10</li>
</ul></li>
<li><code>x &lt;- nchar("hello")</code>
<ul>
<li>This will count the number of letters in the word “hello” (e.g. 5), then save it as a variable called x</li>
</ul></li>
</ul>
<p>Watch this short video to learn three important facts about functions:</p>
<p><a href="http://vimeo.com/220490105" title="R functions"><img src="images/Fig_01_07VIDEO_Functions.png" alt="Function basics" /></a></p>
<p>One example of a function is <code>file.choose()</code> (not how I put the parentheses in this lab book so you can see it is a command). This command will let you interactively select a file and print the address out onto the screen.</p>
<p>Try each of these out in your console for the file.choose() command, leaving the parentheses blank.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="index.html#cb27-1"></a><span class="co"># Typing this into the console will print out the underlying code</span></span>
<span id="cb27-2"><a href="index.html#cb27-2"></a>file.choose </span>
<span id="cb27-3"><a href="index.html#cb27-3"></a></span>
<span id="cb27-4"><a href="index.html#cb27-4"></a><span class="co"># Typing it WITH parentheses will run the command.  </span></span>
<span id="cb27-5"><a href="index.html#cb27-5"></a><span class="kw">file.choose</span>()</span>
<span id="cb27-6"><a href="index.html#cb27-6"></a></span>
<span id="cb27-7"><a href="index.html#cb27-7"></a><span class="co"># Typing a ? in front will open the help file for that command</span></span>
<span id="cb27-8"><a href="index.html#cb27-8"></a>?file.choose</span></code></pre></div>
<p>Sometimes we need to give the command some additional information. Anything we wish to tell the command should be included inside the inside the parentheses (separated by commas). The command will literally only know about the stuff inside the parentheses.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="index.html#cb28-1"></a><span class="kw">sin</span>(<span class="dv">1</span>) <span class="co"># trigonometry functions.  Apply the sine function to the number 1. </span></span></code></pre></div>
<pre><code>## [1] 0.841471</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="index.html#cb30-1"></a><span class="kw">log</span>(<span class="dv">10</span>) <span class="co"># natural logarithm.  Take the natural logarithm of the number 10. </span></span></code></pre></div>
<pre><code>## [1] 2.302585</code></pre>
<p>This following command will plot the number 1 to 10 against the numbers 12 to 20, along with some axis labels. When you run this, the plot will show up in the plots tab.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="index.html#cb32-1"></a><span class="co"># plot the numbers 1 to 10 against the numbers 11 to 20</span></span>
<span id="cb32-2"><a href="index.html#cb32-2"></a><span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>,<span class="dv">11</span><span class="op">:</span><span class="dv">20</span>,<span class="dt">col=</span><span class="st">&quot;dark blue&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;x values&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;STAT-462 is the best&quot;</span>) </span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>If you are feeling lost, <a href="https://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/" class="uri">https://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/</a>
is a really good website which goes over a lot of this in more detail. A lot of this is based on their work.</p>
</div>
</div>
<div id="S.Tutorial.1D" class="section level2">
<h2><span class="header-section-number">1.4</span> Tutorial 1D: Packages</h2>
<p>There are now several million commands/functions available for you to use in R. To make sure your computer doesn’t get overwhelmed, it doesn’t load all of these at once. In fact many need to be downloaded from the internet.</p>
<p>So we have</p>
<ul>
<li>R: The programming language itself</li>
<li>Functions: Specific commands or actions written in the R language</li>
<li>Packages: Commands are grouped into bundles/apps called packages, which we download from the internet and load every time we need them.</li>
</ul>
<p>A close analogy is your phone. There are millions of apps available from banking, to social media to camera filters. You don’t have every app in the world installed on your phone - and you don’t have every app you <em>do</em> download running at the same time.</p>
<p>This is the same for R:</p>
<ul>
<li>You <em>download and install</em> packages from the internet that you might need. This can be done by clicking the install button in the Packages tab. Or you can use the <code>install.packages()</code> command. You only ever need to do this once.</li>
<li>To actually run the commands in the package you need to load/run them - just in the way you tap an app to start it. This can be done using the <code>library()</code> command.</li>
</ul>
<p>Now we are going to download some packages from the internet and install them. You must be connected to the internet to make this happen! In the console, type the following commands, or click the “Install” button in the packages tab (next to plots) and find the package name. If it asks if you want to install dependencies, say yes.</p>
<p>If R gives you warnings about rtools, ignore them or follow the instructions at the top to install R-Tools.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="index.html#cb33-1"></a><span class="co"># COPY/PASTE THESE INTO YOUR CONSOLE AND LET THEM RUN. </span></span>
<span id="cb33-2"><a href="index.html#cb33-2"></a><span class="co">#(These are hopefully all the packages for the course, so it&#39;s a one off download)</span></span>
<span id="cb33-3"><a href="index.html#cb33-3"></a></span>
<span id="cb33-4"><a href="index.html#cb33-4"></a><span class="kw">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>) <span class="co"># Lots of data processing commands</span></span>
<span id="cb33-5"><a href="index.html#cb33-5"></a><span class="kw">install.packages</span>(<span class="st">&quot;knitr&quot;</span>)     <span class="co"># Helps make good output files</span></span>
<span id="cb33-6"><a href="index.html#cb33-6"></a><span class="kw">install.packages</span>(<span class="st">&quot;rmarkdown&quot;</span>) <span class="co"># Helps make good output files</span></span>
<span id="cb33-7"><a href="index.html#cb33-7"></a><span class="kw">install.packages</span>(<span class="st">&quot;lattice&quot;</span>)   <span class="co"># Makes nice plots</span></span>
<span id="cb33-8"><a href="index.html#cb33-8"></a><span class="kw">install.packages</span>(<span class="st">&quot;RColorBrewer&quot;</span>) <span class="co"># Makes nice color-scales</span></span>
<span id="cb33-9"><a href="index.html#cb33-9"></a><span class="kw">install.packages</span>(<span class="st">&quot;ISLR&quot;</span>)      <span class="co"># contains a credit dataset</span></span>
<span id="cb33-10"><a href="index.html#cb33-10"></a><span class="kw">install.packages</span>(<span class="st">&quot;yarrr&quot;</span>)     <span class="co"># contains a toy dataset about pirates</span></span>
<span id="cb33-11"><a href="index.html#cb33-11"></a><span class="kw">install.packages</span>(<span class="st">&quot;skimr&quot;</span>)     <span class="co"># Summary statistics</span></span>
<span id="cb33-12"><a href="index.html#cb33-12"></a><span class="kw">install.packages</span>(<span class="st">&quot;Stat2Data&quot;</span>) <span class="co"># Regression specific commands</span></span>
<span id="cb33-13"><a href="index.html#cb33-13"></a><span class="kw">install.packages</span>(<span class="st">&quot;olsrr&quot;</span>)     <span class="co"># Regression specific commands</span></span>
<span id="cb33-14"><a href="index.html#cb33-14"></a><span class="kw">install.packages</span>(<span class="st">&quot;nortest&quot;</span>)   <span class="co"># Regression specific commands</span></span>
<span id="cb33-15"><a href="index.html#cb33-15"></a><span class="kw">install.packages</span>(<span class="st">&quot;lmtest&quot;</span>)    <span class="co"># Regression specific commands</span></span>
<span id="cb33-16"><a href="index.html#cb33-16"></a><span class="kw">install.packages</span>(<span class="st">&quot;IMTest&quot;</span>)    <span class="co"># Regression specific commands </span></span>
<span id="cb33-17"><a href="index.html#cb33-17"></a><span class="kw">install.packages</span>(<span class="st">&quot;MASS&quot;</span>)      <span class="co"># Regression specific commands</span></span>
<span id="cb33-18"><a href="index.html#cb33-18"></a><span class="kw">install.packages</span>(<span class="st">&quot;moderndive&quot;</span>)<span class="co"># Regression specific commands</span></span>
<span id="cb33-19"><a href="index.html#cb33-19"></a><span class="kw">install.packages</span>(<span class="st">&quot;corrplot&quot;</span>)  <span class="co"># correlation plots</span></span>
<span id="cb33-20"><a href="index.html#cb33-20"></a><span class="kw">install.packages</span>(<span class="st">&quot;ggpubr&quot;</span>)    <span class="co"># Nice regression plots</span></span>
<span id="cb33-21"><a href="index.html#cb33-21"></a><span class="kw">install.packages</span>(<span class="st">&quot;car&quot;</span>)       <span class="co"># this one sometimes has problems, don&#39;t panic if you get errors</span></span></code></pre></div>
<p>You will see a load of red text appear in the console as it tells you its very detailed status of how it’s downloading and installing. Don’t panic! It might also take several minutes to do this, longer on a bad internet connection. We are doing this as a one off at the start of the course.</p>
<p>When you have run all the commands and waited until they have finished running (remember, when it is done, you should see the little “&gt;” symbol in the console waiting for your next command), we want to check if they have installed successfully onto your computer.</p>
<p>To do this we are going to load them using the library command:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="index.html#cb34-1"></a><span class="kw">library</span>(<span class="st">&quot;tidyverse&quot;</span>) <span class="co"># Lots of data processing commands</span></span>
<span id="cb34-2"><a href="index.html#cb34-2"></a><span class="kw">library</span>(<span class="st">&quot;knitr&quot;</span>)     <span class="co"># Helps make good output files</span></span>
<span id="cb34-3"><a href="index.html#cb34-3"></a><span class="kw">library</span>(<span class="st">&quot;rmarkdown&quot;</span>) <span class="co"># Helps make good output files</span></span>
<span id="cb34-4"><a href="index.html#cb34-4"></a><span class="kw">library</span>(<span class="st">&quot;lattice&quot;</span>)   <span class="co"># Makes nice plots</span></span>
<span id="cb34-5"><a href="index.html#cb34-5"></a><span class="kw">library</span>(<span class="st">&quot;RColorBrewer&quot;</span>) <span class="co"># Makes nice color-scales</span></span>
<span id="cb34-6"><a href="index.html#cb34-6"></a><span class="kw">library</span>(<span class="st">&quot;ISLR&quot;</span>)      <span class="co"># contains a credit dataset</span></span>
<span id="cb34-7"><a href="index.html#cb34-7"></a><span class="kw">library</span>(<span class="st">&quot;yarrr&quot;</span>)     <span class="co"># contains a toy dataset about pirates</span></span>
<span id="cb34-8"><a href="index.html#cb34-8"></a><span class="kw">library</span>(<span class="st">&quot;skimr&quot;</span>)     <span class="co"># Summary statistics</span></span>
<span id="cb34-9"><a href="index.html#cb34-9"></a><span class="kw">library</span>(<span class="st">&quot;Stat2Data&quot;</span>) <span class="co"># Regression specific commands</span></span>
<span id="cb34-10"><a href="index.html#cb34-10"></a><span class="kw">library</span>(<span class="st">&quot;olsrr&quot;</span>)     <span class="co"># Regression specific commands</span></span>
<span id="cb34-11"><a href="index.html#cb34-11"></a><span class="kw">library</span>(<span class="st">&quot;nortest&quot;</span>)   <span class="co"># Regression specific commands</span></span>
<span id="cb34-12"><a href="index.html#cb34-12"></a><span class="kw">library</span>(<span class="st">&quot;lmtest&quot;</span>)    <span class="co"># Regression specific commands</span></span>
<span id="cb34-13"><a href="index.html#cb34-13"></a><span class="kw">library</span>(<span class="st">&quot;IMTest&quot;</span>)    <span class="co"># Regression specific commands </span></span>
<span id="cb34-14"><a href="index.html#cb34-14"></a><span class="kw">library</span>(<span class="st">&quot;MASS&quot;</span>)      <span class="co"># Regression specific commands</span></span>
<span id="cb34-15"><a href="index.html#cb34-15"></a><span class="kw">library</span>(<span class="st">&quot;moderndive&quot;</span>)<span class="co"># Regression specific commands</span></span>
<span id="cb34-16"><a href="index.html#cb34-16"></a><span class="kw">library</span>(<span class="st">&quot;corrplot&quot;</span>)  <span class="co"># correlation plots</span></span>
<span id="cb34-17"><a href="index.html#cb34-17"></a><span class="kw">library</span>(<span class="st">&quot;ggpubr&quot;</span>)    <span class="co"># Nice regression plots</span></span>
<span id="cb34-18"><a href="index.html#cb34-18"></a><span class="kw">library</span>(<span class="st">&quot;car&quot;</span>)       <span class="co"># this one sometimes has problems, don&#39;t panic if you get errors</span></span></code></pre></div>
<p>If you have managed to install them successfully, often nothing happens - this is great! It means it loaded the package without errors.</p>
<p>Sometimes, it will tell you friendly messages. For example, this is what shows up when you install the tidyverse package. It is telling you the sub-packages that it downloaded and also that some commands, like filter - now have a different meaning. E.g. originally the filter command did one thing, but now the tidyverse package has made filter do something else.</p>
<div class="figure"><span id="fig:tidyverset"></span>
<img src="images/Fig_1_15Tidyverse.png" alt="Tidyverse install messages" width="766" />
<p class="caption">
Figure 1.6: Tidyverse install messages
</p>
</div>
<p><strong>To find out if what you are seeing is a friendly message or an error, run the command again. If you run it a second time and there is no error then nothing should happen.</strong></p>
<p>! <strong>IMPORTANT</strong> If you see some red errors here after multiple attempts running the commands, we will have to fix what your computer is doing together. If you see errors, then take a screenshot of the full page and talk to a TA or Dr Greatrex, or post on the Lab 1 discussion.</p>
<p>Note - you don’t need to submit anything for lab challenge 2 - it’s here to make the rest of the semester run smoothly. Your only action is to reach out if there are errors.</p>
</div>
<div id="S.Tutorial.1E" class="section level2">
<h2><span class="header-section-number">1.5</span> Tutorial 1E: R Markdown basics</h2>
<div id="S.Tutorial.1E.1" class="section level3">
<h3><span class="header-section-number">1.5.1</span> What is R-markdown?</h3>
<p>So far, we’ve been typing commands into the console, but these will all be lost once you close R. Equally, it’s hard to remember or reproduce the analysis you have done . So we will now move onto writing code commands that you can save and submit.</p>
<p>There are several types of document that you can create and save in R-Studio.</p>
<ul>
<li><p>A basic script (the filetype is .r). This is simply just a blank document where you can save code commands. When you “run” the commands in the script, R simply copy/pastes the commands over to the console.</p></li>
<li><p>An R-Notebook or R-Markdown document (the filetype is .Rmd). These are documents you can use to write a report with normal text/pictures, but and also include both your R code and output. You can turn these into reports, websites, blogs, presentations or applications. For example these instructions are created using a markdown document.</p></li>
</ul>
<p>In this course we are going to focus on the R-Markdown format and you are going to submit your labs as html files.</p>
</div>
<div id="S.Tutorial.1E.2" class="section level3">
<h3><span class="header-section-number">1.5.2</span> Creating a markdown document</h3>
<p>Time to make your own. Go to the File menu on the top left, then click New File - R-Markdown. It will ask you to name and save your file. Call it STAT-462 Lab 1.</p>
<div class="figure"><span id="fig:startmarkdownt"></span>
<img src="images/Fig_01_08_Markdown.png" alt="You should see TWO new files appear in your lab 1 folder" width="810" />
<p class="caption">
Figure 1.7: You should see TWO new files appear in your lab 1 folder
</p>
</div>
<p>A file should appear on your screen - your first markdown script. Essentially, we have some space for text, some space for code, and a space at the top of the file where we can add information about themes/styles etc. Each file contains some friendly text to explain what is going on, which I have annotated here.</p>
<div class="figure"><span id="fig:markdownt"></span>
<img src="images/Fig_1_09Markdown.png" alt="You should see TWO new files appear in your lab 1 folder" width="972" />
<p class="caption">
Figure 1.8: You should see TWO new files appear in your lab 1 folder
</p>
</div>
<p>Code chunks are the grey areas and are essentially “mini consoles”. If you click on the little right triangle arrow at the top-right of the code chunk, you can run the plot command, and a plot will appear, running the code.</p>
<p>Note, it no longer runs in the console. You can still copy things into the console, by clicking on the line you want to run and pressing Ctrl-Enter / command-Enter.</p>
<p>Let’s try this. On line 11, delete <code>plot(cars)</code> and type <code>1+1</code>. Now press the green arrow and the answer should appear directly under your code chunk.</p>
<p>Now click at the end of the script, around line 20 and press the green insert button (top right in the script menu icons). Insert a new R code chunk. Inside, type <code>1+2</code> and run it. So you can see that you can have text/pictures/videos etc, and code chunks interspersed throughout it.</p>
<p><em>Now press the “knit” button (right next to the save button)</em>.</p>
<p>It will first ask you to save. Save it as STAT462_Lab1_PSU.ID e.g. STAT462_Lab1_hlg5155. Then, this should make a new file pop-up, a html pretty version of your code and output. If you go to your lab 1 folder, you will see that this has appeared next to your .Rmd file.</p>
</div>
<div id="S.Tutorial.1E.3" class="section level3">
<h3><span class="header-section-number">1.5.3</span> “Friendly text”</h3>
<p>Much of what you see on your screen when you open a notebook document is simply a friendly introduction to RStudio.</p>
<p>So your notebook file is essentially a Word document with the ability to add in “mini R-consoles”, AKA your code chunks. Imagine every time you opened a new word document, it included some “friendly text” (<em>“hi, this is a word document, this is how you do bold text, this is how you save”</em>). This is great the first time you ever use Word, but kind of a pain after that.</p>
<p>RStudio actually does this. Every time you open a notebook file, you actually <em>do</em> get this friendly text, explaining how to use a notebook file. Read it, make sure you understand what it is telling you, then delete all of it. So delete from line 6 to the end. The stuff left over is your YAML code which tells R how to create the final html file. DON’T TOUCH THAT.</p>
<div class="figure"><span id="fig:friendlyt"></span>
<img src="images/Fig_01_10Friendlytext.png" alt="You should see TWO new files appear in your lab 1 folder" width="910" />
<p class="caption">
Figure 1.9: You should see TWO new files appear in your lab 1 folder
</p>
</div>
</div>
</div>
<div id="S.Tutorial.2A" class="section level2">
<h2><span class="header-section-number">1.6</span> Tutorial 2A: Getting help in R</h2>
<p>There are going to be many occasions when either you are not sure what to do in R or something is not working. Here are some of the places I get help:</p>
<div id="S.Tutorial.2A.1" class="section level3">
<h3><span class="header-section-number">1.6.1</span> Help on a specific command</h3>
<p>You can type <code>?function_name</code> into the console where [name] is the CASE SENSITIVE name of the command. For example, you can find help on the boxplot command by typing <code>?boxplot</code> or <code>help(boxplot)</code>.</p>
<ul>
<li><p>The top part of each help file will show you a list of the parameters that you can use to modify the command. For example in the boxplot help file you can see that the col parameter can be used to change the boxplot colour.</p></li>
<li><p>The middle part of the help file contains details about the command for example the background or further reading</p></li>
<li><p>The last part of the help file contains worked examples that you can literally copy/paste into the console too see how they work.</p></li>
</ul>
<p>If you’re <em>sure</em> you typed the name correct but it can’t find the help-file, then you probably first need to load the package containing the command. For example <code>?ggqqplot</code> will not work before you use <code>library("ggpubr")</code> to load the <code>ggpubr</code> package.</p>
</div>
<div id="S.Tutorial.2A.2" class="section level3">
<h3><span class="header-section-number">1.6.2</span> Finding a command name</h3>
<p>Let’s say that you want to run a Wilks Shapiro test but you cannot remember what the command is called. In the console try typing <code>??"search_text"</code> or <code>help.search("search_text")</code> e.g. try <code>??"shapiro"</code> or <code>help.search("shapiro")</code>.</p>
<p>Note, there are now quote marks around the text you are searching for. To seek help on special operators, use quotes or back-ticks e.g. <code>?"&lt;-"</code>.</p>
<p><code>help.search("shapiro")</code> will search through every R help file on your computer that includes the word “shapiro”.</p>
<p><img src="images/Fig_02_01HelpFile.png" width="1100" /></p>
<p>You can see that there are a three commands I can choose from (I might have more than you here). For each command you can see the package containing the command, followed by :: then the command name. Clicking on it brings up the help file.</p>
<p>Remember to actually use any command in R, you first need to load the relevant package. For example, if I wanted to use the nortest version of sf.test, then I would first need to include the command <code>library(nortest)</code> in order for it to be available.</p>
</div>
<div id="S.Tutorial.2A.3" class="section level3">
<h3><span class="header-section-number">1.6.3</span> Asking the internet:</h3>
<div class="figure"><span id="fig:xkcdt"></span>
<img src="images/Fig_02_02XKCD.png" alt="This may be a cartoon but it's genuinely how I debug my code!" width="732" />
<p class="caption">
Figure 1.10: This may be a cartoon but it’s genuinely how I debug my code!
</p>
</div>
<p>If your code isn’t working. Google is a great tool and you have full permission to search google to debug your code - I guarantee someone will have seen your error code before. I often literally copy/paste an error code into google and see what comes up. Or search google for things like “how to add an image R markdown”.</p>
<p>One good place to search is Stack Overflow. To go directly to R-related topics, visit <a href="http://stackoverflow.com/questions/tagged/r" class="uri">http://stackoverflow.com/questions/tagged/r</a>. Here’s how to ask a good question: <a href="https://stackoverflow.com/help/how-to-ask" class="uri">https://stackoverflow.com/help/how-to-ask</a></p>
<p>When asking for help, typing the command <code>sessionInfo()</code> into the console will print out the version of R and the packages you have loaded. This can be useful for debugging any issues.</p>
<p>You also always have lab sessions to ask questions or the discussion boards at any time.</p>
</div>
<div id="S.Tutorial.2A.4" class="section level3">
<h3><span class="header-section-number">1.6.4</span> General help &amp; cheatsheets</h3>
<p>Within R, try running <code>help.start()</code> in the console (remember to include the empty parentheses or R won’t realise it’s a command). This brings up all the manuals R has available on your computer. An introduction to R is particularly useful. Click on it and have a look around.</p>
<p>There are also some really good cheat-sheets out there:</p>
<ul>
<li>MARKDOWN cheat-sheet: go to the help menu at the very top of your screen. Click <code>Markdown Quick Reference</code>.</li>
<li>Loads more cheatsheets: <a href="https://rstudio.com/resources/cheatsheets/" class="uri">https://rstudio.com/resources/cheatsheets/</a></li>
<li>The R graph gallery <a href="https://www.r-graph-gallery.com/" class="uri">https://www.r-graph-gallery.com/</a> contains code for many beautiful plots that you can make.</li>
<li>Googling the name of a package often leads to a website with nice tutorials. For example, I found this for the paletteer package <a href="https://emilhvitfeldt.github.io/paletteer/" class="uri">https://emilhvitfeldt.github.io/paletteer/</a>.</li>
<li>A nice markdown summary - <a href="https://ourcodingclub.github.io/tutorials/rmarkdown/" class="uri">https://ourcodingclub.github.io/tutorials/rmarkdown/</a> with answers to things like preview vs knit.</li>
</ul>
</div>
</div>
<div id="S.Tutorial.2B" class="section level2">
<h2><span class="header-section-number">1.7</span> Tutorial 2B: Markdown formats</h2>
<p>The aim of this tutorial is to make your markdown reports more professional and easy to read. In future weeks we will continue to expand this work so that by the end of the course, you can make highly professional interactive reports. For example, <a href="https://rmarkdown.rstudio.com/formats.html">click here</a> for all the types of document you could easily turn your report into.</p>
<div id="S.Tutorial.2B.1" class="section level3">
<h3><span class="header-section-number">1.7.1</span> Editing YAML code</h3>
<p>This is the code at the top of your file (Figure <a href="index.html#fig:friendlyt">1.9</a>). It controls how your final output looks and which type of output it becomes. When you create a markdown file, your code will look like one of these two options (one created using notebook and one markdown - either are fine)</p>
<div class="figure"><span id="fig:yamlt"></span>
<img src="images/Fig02_03YAMLCode.png" alt="One created using a notebook and one using a markdown" width="868" />
<p class="caption">
Figure 1.11: One created using a notebook and one using a markdown
</p>
</div>
<p>No matter what you have, it is useful to change the YAML code so that it looks like this, but with your name &amp; Lab 2.</p>
<p>Note, if you copy/paste this and it doesn’t work, sometimes the quote marks copy weirdly from the internet - try deleting and retyping the quotes.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="index.html#cb35-1"></a><span class="op">---</span></span>
<span id="cb35-2"><a href="index.html#cb35-2"></a>title<span class="op">:</span><span class="st"> &quot;STAT-462: Lab 2&quot;</span></span>
<span id="cb35-3"><a href="index.html#cb35-3"></a>author<span class="op">:</span><span class="st"> &quot;Helen Greatrex&quot;</span></span>
<span id="cb35-4"><a href="index.html#cb35-4"></a>date<span class="op">:</span><span class="st"> &quot;`r Sys.Date()`&quot;</span></span>
<span id="cb35-5"><a href="index.html#cb35-5"></a>output<span class="op">:</span></span>
<span id="cb35-6"><a href="index.html#cb35-6"></a><span class="st">  </span>html_document<span class="op">:</span></span>
<span id="cb35-7"><a href="index.html#cb35-7"></a><span class="st">    </span>toc<span class="op">:</span><span class="st"> </span>true</span>
<span id="cb35-8"><a href="index.html#cb35-8"></a>    toc_float<span class="op">:</span><span class="st"> </span>yes</span>
<span id="cb35-9"><a href="index.html#cb35-9"></a>    number_sections<span class="op">:</span><span class="st"> </span>yes</span>
<span id="cb35-10"><a href="index.html#cb35-10"></a>    theme<span class="op">:</span><span class="st"> </span>lumen</span>
<span id="cb35-11"><a href="index.html#cb35-11"></a>    df_print<span class="op">:</span><span class="st"> </span>paged</span>
<span id="cb35-12"><a href="index.html#cb35-12"></a>  html_notebook<span class="op">:</span></span>
<span id="cb35-13"><a href="index.html#cb35-13"></a><span class="st">    </span>toc<span class="op">:</span><span class="st"> </span>true</span>
<span id="cb35-14"><a href="index.html#cb35-14"></a>    toc_float<span class="op">:</span><span class="st"> </span>yes</span>
<span id="cb35-15"><a href="index.html#cb35-15"></a>    number_sections<span class="op">:</span><span class="st"> </span>yes</span>
<span id="cb35-16"><a href="index.html#cb35-16"></a>    theme<span class="op">:</span><span class="st"> </span>lumen    </span>
<span id="cb35-17"><a href="index.html#cb35-17"></a><span class="op">---</span></span></code></pre></div>
<p>Now, save your file, or click “preview” at the top of the script. See if it works.</p>
<p>There is a reasonable chance this won’t work first time around, as editing the YAML code can be a pain. It is very case and space sensitive. For example, the spaces at the start of some lines are important and are created using the TAB KEY, not the space bar. There is one TAB key before html_notebook (which is now on a new line). There are two TAB KEYS before toc, toc_float, number_sections and theme.</p>
<p><em>Don’t continue until you can make and view your html or nb.html file. If it doesn’t work, ask for help before moving on</em></p>
<p>The elements we just added are:</p>
<ul>
<li>The title</li>
<li>The author</li>
<li>Today’s date</li>
<li>A floating table of contents and numbered sections (this won’t appear until you start typing section headings)</li>
<li>The document is now in the lumen theme. <strong>You can choose other themes for markdown documents here. <a href="https://www.datadreaming.org/post/r-markdown-theme-gallery/" class="uri">https://www.datadreaming.org/post/r-markdown-theme-gallery/</a></strong></li>
</ul>
<p>There are many more details about different options you can add here: <a href="https://rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf" class="uri">https://rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf</a></p>
<p>If you want to get really fancy, there is an interesting package to help you design YAML code here: <a href="https://education.rstudio.com/blog/2019/10/tools-for-teaching-yaml-with-ymlthis/" class="uri">https://education.rstudio.com/blog/2019/10/tools-for-teaching-yaml-with-ymlthis/</a></p>
</div>
<div id="S.Tutorial.2B.2" class="section level3">
<h3><span class="header-section-number">1.7.2</span> Text formats</h3>
<p>R-Markdown uses text formatting a bit like LateX rather than word where you format the text as you write. First off - there are many cheat-sheets out there, but I particularly like this one <a href="https://www.markdownguide.org/basic-syntax/" class="uri">https://www.markdownguide.org/basic-syntax/</a>.</p>
<p>One important way to make your R Markdown documents look more professional is to add in headings, sub-headings and text formats. Today we will look at headings and bold/italic text.</p>
<div class="figure"><span id="fig:formatst"></span>
<img src="images/Fig02_04Markdownformat.png" alt="A typical Rmd file (right) and its output (left) - note you need to click on the contents bar to expand it" width="1652" />
<p class="caption">
Figure 1.12: A typical Rmd file (right) and its output (left) - note you need to click on the contents bar to expand it
</p>
</div>
<p>First, go to the help menu at the very top of your screen (might be hidden) and click Markdown quick reference. This will bring up a cheat-sheet.</p>
<div class="figure"><span id="fig:quickreft"></span>
<img src="images/Fig02_05markdownref.png" alt="The top menu might be hidden" width="1146" />
<p class="caption">
Figure 1.13: The top menu might be hidden
</p>
</div>
<p><strong>Paragraphs and white space - READ THIS:</strong></p>
<p>R is very sensitive to blank white lines. Put them everywhere. Put a blank line between paragraphs, before/after headings, before lists, before/after code chunks…. If your formatting isn’t working well, chances are there isn’t a blank line before or after it.</p>
<p><strong>Headings:</strong></p>
<p><em>Inside</em> a code chunk, the # symbol allows you to write mini comments that help explain the command e.g. </p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="index.html#cb36-1"></a><span class="co"># calculate 1+1 and 2+2</span></span>
<span id="cb36-2"><a href="index.html#cb36-2"></a><span class="dv">1</span><span class="op">+</span><span class="dv">1</span></span>
<span id="cb36-3"><a href="index.html#cb36-3"></a><span class="co">## [1] 2</span></span>
<span id="cb36-4"><a href="index.html#cb36-4"></a><span class="dv">2</span><span class="op">+</span><span class="dv">2</span></span>
<span id="cb36-5"><a href="index.html#cb36-5"></a><span class="co">## [1] 4</span></span></code></pre></div>
<p><em>Outside</em> a code chunk, the # symbol makes a heading, AS LONG AS YOU HAVE A WHITE LINE ABOVE AND BELOW. Have a look at Figure <a href="index.html#fig:quickreft">1.13</a> for an example. Including headings this way allows automatic section numbering and will allow the table of contents to automatically be created. In the script itself the headings won’t show up - you will only see them when you press knit.</p>
<p><strong>Bold and italic:</strong></p>
<p>Putting stars or _ around your text will make it bold or italic (or both). Again have a look at Figure <a href="index.html#fig:quickreft">1.13</a> and the cheat-sheet. Interestingly (and annoyingly), there is no simple way to underline text. In the script itself the text formatting won’t show up, you will only see them when you press knit.</p>
</div>
</div>
<div id="S.Tutorial.2C" class="section level2">
<h2><span class="header-section-number">1.8</span> Tutorial 2C: Selecting &amp; summarising data</h2>
<div id="S.Tutorial.2C.1" class="section level3">
<h3><span class="header-section-number">1.8.1</span> Data.frame introduction</h3>
<p>Most of the data we will look at is in “data.frame” format. This is a table, just like an excel spreadsheet, with one row for each observation and one column for each variable. Each column has a column name.</p>
<p>Next week we will work on loading our own data into R. This week we will focus on in-built R datasets.</p>
<p>Let’s choose one now. I’m going to work with the pirates dataset from the <code>yarrr</code> package. We can choose the data here.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="index.html#cb37-1"></a><span class="kw">library</span>(yarrr)</span>
<span id="cb37-2"><a href="index.html#cb37-2"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb37-3"><a href="index.html#cb37-3"></a>?pirates</span>
<span id="cb37-4"><a href="index.html#cb37-4"></a>dataset &lt;-<span class="st"> </span>pirates</span></code></pre></div>
<p>To have a look at the data there are many options. You can either:</p>
<ul>
<li>click on its name in the environment tab</li>
<li>Type its name into the console or into a code chunk (e.g. for our table, type <code>dataset</code> into the console or a code chunk)</li>
<li>Run the command <code>View(variable_name)</code> (View is a command from the tidyverse package)</li>
<li>Run the command <code>print(variable_name)</code></li>
<li>Run the command <code>head(variable_name)</code> to see the first 6 lines or so (good for quick checks)</li>
</ul>
<p>For example</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="index.html#cb38-1"></a><span class="co"># Note, there are more columns to the right, use the arrow to see</span></span>
<span id="cb38-2"><a href="index.html#cb38-2"></a><span class="kw">head</span>(dataset)</span></code></pre></div>
<pre><code>##   id    sex age height weight
## 1  1   male  28 173.11   70.5
## 2  2   male  31 209.25  105.6
## 3  3   male  26 169.95   77.1
## 4  4 female  31 144.29   58.5
## 5  5 female  41 157.85   58.4
## 6  6   male  26 190.20   85.4
##   headband college tattoos
## 1      yes   JSSFP       9
## 2      yes   JSSFP       9
## 3      yes    CCCC      10
## 4       no   JSSFP       2
## 5      yes   JSSFP       9
## 6      yes    CCCC       7
##   tchests parrots
## 1       0       0
## 2      11       0
## 3      10       1
## 4       0       2
## 5       6       4
## 6      19       0
##   favorite.pirate sword.type
## 1    Jack Sparrow    cutlass
## 2    Jack Sparrow    cutlass
## 3    Jack Sparrow    cutlass
## 4    Jack Sparrow   scimitar
## 5            Hook    cutlass
## 6    Jack Sparrow    cutlass
##   eyepatch sword.time
## 1        1       0.58
## 2        0       1.11
## 3        1       1.44
## 4        1      36.11
## 5        1       0.11
## 6        1       0.59
##   beard.length
## 1           16
## 2           21
## 3           19
## 4            2
## 5            0
## 6           17
##             fav.pixar grogg
## 1      Monsters, Inc.    11
## 2              WALL-E     9
## 3          Inside Out     7
## 4          Inside Out     9
## 5          Inside Out    14
## 6 Monsters University     7</code></pre>
<p>To see what the column names are, you can use the <code>names(dataset)</code> command</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="index.html#cb40-1"></a><span class="kw">names</span>(dataset)</span></code></pre></div>
<pre><code>##  [1] &quot;id&quot;             
##  [2] &quot;sex&quot;            
##  [3] &quot;age&quot;            
##  [4] &quot;height&quot;         
##  [5] &quot;weight&quot;         
##  [6] &quot;headband&quot;       
##  [7] &quot;college&quot;        
##  [8] &quot;tattoos&quot;        
##  [9] &quot;tchests&quot;        
## [10] &quot;parrots&quot;        
## [11] &quot;favorite.pirate&quot;
## [12] &quot;sword.type&quot;     
## [13] &quot;eyepatch&quot;       
## [14] &quot;sword.time&quot;     
## [15] &quot;beard.length&quot;   
## [16] &quot;fav.pixar&quot;      
## [17] &quot;grogg&quot;</code></pre>
<p>Or look at the summary</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="index.html#cb42-1"></a><span class="kw">summary</span>(dataset) </span></code></pre></div>
<pre><code>##        id        
##  Min.   :   1.0  
##  1st Qu.: 250.8  
##  Median : 500.5  
##  Mean   : 500.5  
##  3rd Qu.: 750.2  
##  Max.   :1000.0  
##      sex           
##  Length:1000       
##  Class :character  
##  Mode  :character  
##                    
##                    
##                    
##       age       
##  Min.   :11.00  
##  1st Qu.:24.00  
##  Median :27.00  
##  Mean   :27.36  
##  3rd Qu.:31.00  
##  Max.   :46.00  
##      height     
##  Min.   :129.8  
##  1st Qu.:161.4  
##  Median :169.9  
##  Mean   :170.2  
##  3rd Qu.:178.5  
##  Max.   :209.2  
##      weight      
##  Min.   : 33.00  
##  1st Qu.: 62.08  
##  Median : 69.55  
##  Mean   : 69.74  
##  3rd Qu.: 76.90  
##  Max.   :105.60  
##    headband        
##  Length:1000       
##  Class :character  
##  Mode  :character  
##                    
##                    
##                    
##    college         
##  Length:1000       
##  Class :character  
##  Mode  :character  
##                    
##                    
##                    
##     tattoos      
##  Min.   : 0.000  
##  1st Qu.: 7.000  
##  Median :10.000  
##  Mean   : 9.429  
##  3rd Qu.:12.000  
##  Max.   :19.000  
##     tchests      
##  Min.   :  0.00  
##  1st Qu.:  6.00  
##  Median : 15.00  
##  Mean   : 22.69  
##  3rd Qu.: 30.00  
##  Max.   :147.00  
##     parrots      
##  Min.   : 0.000  
##  1st Qu.: 1.000  
##  Median : 2.000  
##  Mean   : 2.819  
##  3rd Qu.: 4.000  
##  Max.   :27.000  
##  favorite.pirate   
##  Length:1000       
##  Class :character  
##  Mode  :character  
##                    
##                    
##                    
##   sword.type       
##  Length:1000       
##  Class :character  
##  Mode  :character  
##                    
##                    
##                    
##     eyepatch    
##  Min.   :0.000  
##  1st Qu.:0.000  
##  Median :1.000  
##  Mean   :0.658  
##  3rd Qu.:1.000  
##  Max.   :1.000  
##    sword.time      
##  Min.   :  0.0000  
##  1st Qu.:  0.2175  
##  Median :  0.5850  
##  Mean   :  2.5427  
##  3rd Qu.:  1.3300  
##  Max.   :169.8800  
##   beard.length  
##  Min.   : 0.00  
##  1st Qu.: 0.00  
##  Median : 9.00  
##  Mean   :10.38  
##  3rd Qu.:20.00  
##  Max.   :40.00  
##   fav.pixar        
##  Length:1000       
##  Class :character  
##  Mode  :character  
##                    
##                    
##                    
##      grogg      
##  Min.   : 0.00  
##  1st Qu.: 8.00  
##  Median :10.00  
##  Mean   :10.14  
##  3rd Qu.:12.00  
##  Max.   :21.00</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="index.html#cb44-1"></a><span class="co"># You can also use the skimr package and skim command here</span></span>
<span id="cb44-2"><a href="index.html#cb44-2"></a><span class="co"># skim(pirates)</span></span></code></pre></div>
<p>To see how many columns and rows there are, you can use the <code>nrow()</code> and <code>ncol()</code> commands</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="index.html#cb45-1"></a><span class="co"># there are 1000</span></span>
<span id="cb45-2"><a href="index.html#cb45-2"></a><span class="kw">nrow</span>(dataset)</span></code></pre></div>
<pre><code>## [1] 1000</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="index.html#cb47-1"></a><span class="kw">ncol</span>(dataset)</span></code></pre></div>
<pre><code>## [1] 17</code></pre>
</div>
<div id="S.Tutorial.2C.2" class="section level3">
<h3><span class="header-section-number">1.8.2</span> Selecting individual values</h3>
<p>You can select rows and columns using SQUARE brackets and [rows,columns]. For example</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="index.html#cb49-1"></a><span class="co">#select row 2 and columns 4,5 &amp; 6 (that&#39;s what the : does, counts from 4 to 6)</span></span>
<span id="cb49-2"><a href="index.html#cb49-2"></a>dataset[<span class="dv">2</span> , <span class="dv">4</span><span class="op">:</span><span class="dv">6</span>]</span></code></pre></div>
<pre><code>##   height weight headband
## 2 209.25  105.6      yes</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="index.html#cb51-1"></a><span class="co">#select rows 1,3 and 5 - plus the height and eyepatch columns</span></span>
<span id="cb51-2"><a href="index.html#cb51-2"></a><span class="co"># the c() command lets you choose whatever values you want and sticks (concatenates) them together</span></span>
<span id="cb51-3"><a href="index.html#cb51-3"></a>dataset[<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>),<span class="kw">c</span>(<span class="st">&quot;height&quot;</span>,<span class="st">&quot;eyepatch&quot;</span>)]</span></code></pre></div>
<pre><code>##   height eyepatch
## 1 173.11        1
## 3 169.95        1
## 5 157.85        1</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="index.html#cb53-1"></a><span class="co"># Leave the right side empty for all the columns</span></span>
<span id="cb53-2"><a href="index.html#cb53-2"></a><span class="co"># e.g this prints all columns of rows 2,3 and 4</span></span>
<span id="cb53-3"><a href="index.html#cb53-3"></a>dataset[<span class="dv">2</span><span class="op">:</span><span class="dv">4</span>, ]</span></code></pre></div>
<pre><code>##   id    sex age height weight
## 2  2   male  31 209.25  105.6
## 3  3   male  26 169.95   77.1
## 4  4 female  31 144.29   58.5
##   headband college tattoos
## 2      yes   JSSFP       9
## 3      yes    CCCC      10
## 4       no   JSSFP       2
##   tchests parrots
## 2      11       0
## 3      10       1
## 4       0       2
##   favorite.pirate sword.type
## 2    Jack Sparrow    cutlass
## 3    Jack Sparrow    cutlass
## 4    Jack Sparrow   scimitar
##   eyepatch sword.time
## 2        0       1.11
## 3        1       1.44
## 4        1      36.11
##   beard.length  fav.pixar
## 2           21     WALL-E
## 3           19 Inside Out
## 4            2 Inside Out
##   grogg
## 2     9
## 3     7
## 4     9</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="index.html#cb55-1"></a><span class="co"># or all the values in a column - I leave the left side blank to select all rows</span></span>
<span id="cb55-2"><a href="index.html#cb55-2"></a><span class="co"># Here I assigned the answer to a new variable called b, That&#39;s why it didn&#39;t print out.</span></span>
<span id="cb55-3"><a href="index.html#cb55-3"></a>b &lt;-<span class="st"> </span>dataset[ ,<span class="kw">c</span>(<span class="st">&quot;college&quot;</span>,<span class="st">&quot;tattoos&quot;</span>)]</span></code></pre></div>
</div>
<div id="S.Tutorial.2C.3" class="section level3">
<h3><span class="header-section-number">1.8.3</span> Selecting a single column</h3>
<p>The easiest way to do this is with the $ symbol. LEARN THIS! It is incredibly useful</p>
<p>For example, to view the age column of the pirates table, I would type <code>pirates$age</code> - so to make a histogram of the pirates ages, I would type</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="index.html#cb56-1"></a><span class="kw">hist</span>(dataset<span class="op">$</span>age,<span class="dt">xlab=</span><span class="st">&quot;Pirates ages&quot;</span>)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
</div>
<div id="S.Tutorial.2C.4" class="section level3">
<h3><span class="header-section-number">1.8.4</span> Selecting mulitple columns</h3>
<p>Sometimes your table is very large and you might only care about a few of the variables. So we could make a new table where we only keep the columns we care about. For example, as described in the R cheatsheet</p>
<div class="figure"><span id="fig:select"></span>
<img src="images/Fig02_06SelectColumns.png" alt="picture from the tidyverse cheatsheet" width="886" />
<p class="caption">
Figure 1.14: picture from the tidyverse cheatsheet
</p>
</div>
<p>Inside the tidyverse packages, there are some easy functions for selecting columns or rows. To choose specific columns, we can use the <code>dplyr::select()</code> function from the tidyverse package or square brackets. Whatever makes you more comfortable.</p>
<p>Let’s select only the “age”,“height”,“sex”,“weight”,“favorite.pirate” and “beard.length” columns:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="index.html#cb57-1"></a><span class="co"># print the column names, so its easier to write the command</span></span>
<span id="cb57-2"><a href="index.html#cb57-2"></a><span class="kw">names</span>(dataset)</span></code></pre></div>
<pre><code>##  [1] &quot;id&quot;             
##  [2] &quot;sex&quot;            
##  [3] &quot;age&quot;            
##  [4] &quot;height&quot;         
##  [5] &quot;weight&quot;         
##  [6] &quot;headband&quot;       
##  [7] &quot;college&quot;        
##  [8] &quot;tattoos&quot;        
##  [9] &quot;tchests&quot;        
## [10] &quot;parrots&quot;        
## [11] &quot;favorite.pirate&quot;
## [12] &quot;sword.type&quot;     
## [13] &quot;eyepatch&quot;       
## [14] &quot;sword.time&quot;     
## [15] &quot;beard.length&quot;   
## [16] &quot;fav.pixar&quot;      
## [17] &quot;grogg&quot;</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="index.html#cb59-1"></a><span class="co"># The &quot;traditional R way&quot;</span></span>
<span id="cb59-2"><a href="index.html#cb59-2"></a>newdata &lt;-<span class="st"> </span>dataset[,<span class="kw">c</span>(<span class="st">&quot;age&quot;</span>,<span class="st">&quot;height&quot;</span>,<span class="st">&quot;sex&quot;</span>,<span class="st">&quot;weight&quot;</span>,<span class="st">&quot;favorite.pirate&quot;</span>,</span>
<span id="cb59-3"><a href="index.html#cb59-3"></a>                      <span class="st">&quot;beard.length&quot;</span>)]</span>
<span id="cb59-4"><a href="index.html#cb59-4"></a></span>
<span id="cb59-5"><a href="index.html#cb59-5"></a><span class="co"># The &quot;tidyverse way&quot;</span></span>
<span id="cb59-6"><a href="index.html#cb59-6"></a><span class="co"># Note, i&#39;m telling it that I want select from the dplyr package because </span></span>
<span id="cb59-7"><a href="index.html#cb59-7"></a><span class="co">#        R wanted to choose a different &quot;select&quot; function</span></span>
<span id="cb59-8"><a href="index.html#cb59-8"></a>identicalnewdata &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">as_tibble</span>(dataset),<span class="kw">c</span>(age,height,weight,</span>
<span id="cb59-9"><a href="index.html#cb59-9"></a>                                                       favorite.pirate,beard.length))</span>
<span id="cb59-10"><a href="index.html#cb59-10"></a></span>
<span id="cb59-11"><a href="index.html#cb59-11"></a><span class="co"># have a look at what we did</span></span>
<span id="cb59-12"><a href="index.html#cb59-12"></a><span class="kw">head</span>(newdata)</span></code></pre></div>
<pre><code>##   age height    sex weight
## 1  28 173.11   male   70.5
## 2  31 209.25   male  105.6
## 3  26 169.95   male   77.1
## 4  31 144.29 female   58.5
## 5  41 157.85 female   58.4
## 6  26 190.20   male   85.4
##   favorite.pirate
## 1    Jack Sparrow
## 2    Jack Sparrow
## 3    Jack Sparrow
## 4    Jack Sparrow
## 5            Hook
## 6    Jack Sparrow
##   beard.length
## 1           16
## 2           21
## 3           19
## 4            2
## 5            0
## 6           17</code></pre>
</div>
<div id="S.Tutorial.2C.5" class="section level3">
<h3><span class="header-section-number">1.8.5</span> Selecting subsets of rows/observations</h3>
<p>Very commonly, we want to select only <em>some</em> rows in our table. For example, let’s say I want to look at the distribution of men’s beard lengths. This means that I only want to select the men in the pirates dataset.</p>
<p>Again there are two ways of doing this:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="index.html#cb61-1"></a><span class="co"># e.g. select rows have the column sex set equal to male</span></span>
<span id="cb61-2"><a href="index.html#cb61-2"></a></span>
<span id="cb61-3"><a href="index.html#cb61-3"></a><span class="co"># The &quot;traditional R way&quot;. You can use either == or %in% for your selection</span></span>
<span id="cb61-4"><a href="index.html#cb61-4"></a>malepirates &lt;-<span class="st"> </span>newdata[<span class="kw">which</span>(newdata<span class="op">$</span>sex <span class="op">%in%</span><span class="st"> &quot;male&quot;</span>),]</span>
<span id="cb61-5"><a href="index.html#cb61-5"></a>malepirates &lt;-<span class="st"> </span>newdata[<span class="kw">which</span>(newdata<span class="op">$</span>sex  <span class="op">==</span><span class="st">  &quot;male&quot;</span>),]</span>
<span id="cb61-6"><a href="index.html#cb61-6"></a></span>
<span id="cb61-7"><a href="index.html#cb61-7"></a><span class="co"># The &quot;tidyverse way&quot;. </span></span>
<span id="cb61-8"><a href="index.html#cb61-8"></a>malepirates &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">filter</span>(newdata, sex <span class="op">==</span><span class="st"> &quot;male&quot;</span>)</span>
<span id="cb61-9"><a href="index.html#cb61-9"></a></span>
<span id="cb61-10"><a href="index.html#cb61-10"></a><span class="co"># have a look at what we did</span></span>
<span id="cb61-11"><a href="index.html#cb61-11"></a><span class="kw">head</span>(malepirates)</span></code></pre></div>
<pre><code>##   age height  sex weight
## 1  28 173.11 male   70.5
## 2  31 209.25 male  105.6
## 3  26 169.95 male   77.1
## 4  26 190.20 male   85.4
## 5  30 183.52 male   84.7
## 6  20 163.65 male   70.0
##   favorite.pirate
## 1    Jack Sparrow
## 2    Jack Sparrow
## 3    Jack Sparrow
## 4    Jack Sparrow
## 5    Jack Sparrow
## 6    Jack Sparrow
##   beard.length
## 1           16
## 2           21
## 3           19
## 4           17
## 5           25
## 6           27</code></pre>
<p>You can also use other symbols to select data</p>
<ul>
<li><code>&gt;=</code> greater than or equal to</li>
<li><code>&gt;</code> greater than</li>
<li><code>==</code> equal to</li>
<li><code>!=</code> NOT equal to</li>
<li><code>&lt;</code> less than</li>
<li><code>&lt;=</code> less than or equal to</li>
</ul>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="index.html#cb63-1"></a><span class="co"># What is the average weight of pirates who are over 150cm tall?</span></span>
<span id="cb63-2"><a href="index.html#cb63-2"></a>tallpirates &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">filter</span>(dataset, height <span class="op">&gt;</span><span class="st"> </span><span class="dv">180</span>)</span>
<span id="cb63-3"><a href="index.html#cb63-3"></a><span class="kw">mean</span>(tallpirates<span class="op">$</span>weight)</span>
<span id="cb63-4"><a href="index.html#cb63-4"></a><span class="co">## [1] 83.9277</span></span></code></pre></div>
<p>Or you could use multiple conditions using the &amp; symbol or | symbol</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="index.html#cb64-1"></a><span class="co"># What is the average weight of MALE pirates who are over 150cm tall?</span></span>
<span id="cb64-2"><a href="index.html#cb64-2"></a>tall.male.pirates &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">filter</span>(dataset, height <span class="op">&gt;</span><span class="st"> </span><span class="dv">180</span> <span class="op">&amp;</span><span class="st"> </span>sex <span class="op">==</span><span class="st"> &quot;male&quot;</span>)</span>
<span id="cb64-3"><a href="index.html#cb64-3"></a><span class="kw">mean</span>(tall.male.pirates<span class="op">$</span>weight)</span>
<span id="cb64-4"><a href="index.html#cb64-4"></a><span class="co">## [1] 84.18984</span></span></code></pre></div>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="index.html#cb65-1"></a><span class="co"># What is the maximum number of tattoos on tall pirates who have at least 1 parrot OR an eyepatch</span></span>
<span id="cb65-2"><a href="index.html#cb65-2"></a>tall.parrot.eye &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">filter</span>(dataset, height <span class="op">&gt;</span><span class="st"> </span><span class="dv">180</span> <span class="op">&amp;</span><span class="st"> </span>(parrots <span class="op">&gt;=</span><span class="st"> </span><span class="dv">1</span> <span class="op">|</span>eyepatch <span class="op">==</span><span class="st"> </span><span class="dv">1</span> ))</span>
<span id="cb65-3"><a href="index.html#cb65-3"></a><span class="kw">max</span>(tall.parrot.eye<span class="op">$</span>tattoos)</span>
<span id="cb65-4"><a href="index.html#cb65-4"></a><span class="co">## [1] 18</span></span></code></pre></div>
</div>
<div id="S.Tutorial.2C.6" class="section level3">
<h3><span class="header-section-number">1.8.6</span> Looking at summary tables</h3>
<p>We often want to see summary statistics of our data. We covered the <code>summary</code> command last week and above. But what about categorical data? Just how many pirates liked Monsters Inc.? We can look at this using the <code>table()</code> command.</p>
<p>This counts the number of rows containing each category. For example, we can see here that 50 pirates out of the 1000 chose Monsters Inc as their favourite film</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="index.html#cb66-1"></a><span class="kw">table</span>(dataset<span class="op">$</span>fav.pixar)</span></code></pre></div>
<pre><code>## 
##        A Bug&#39;s Life 
##                  28 
##               Brave 
##                  21 
##                Cars 
##                  21 
##              Cars 2 
##                  14 
##        Finding Nemo 
##                 162 
##          Inside Out 
##                 304 
## Monsters University 
##                  94 
##      Monsters, Inc. 
##                  50 
##         Ratatouille 
##                   3 
##     The Incredibles 
##                  66 
##           Toy Story 
##                  16 
##         Toy Story 2 
##                  25 
##         Toy Story 3 
##                  13 
##                  Up 
##                 118 
##              WALL-E 
##                  65</code></pre>
<p>We can also go beyond this. For example, let’s break it up by gender - where we can see that 2 non-binary pirates liked the film.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="index.html#cb68-1"></a><span class="kw">table</span>(dataset<span class="op">$</span>fav.pixar,dataset<span class="op">$</span>sex )</span></code></pre></div>
<pre><code>##                      
##                       female
##   A Bug&#39;s Life            21
##   Brave                    7
##   Cars                    10
##   Cars 2                   9
##   Finding Nemo            67
##   Inside Out             139
##   Monsters University     43
##   Monsters, Inc.          20
##   Ratatouille              1
##   The Incredibles         34
##   Toy Story                6
##   Toy Story 2             10
##   Toy Story 3              7
##   Up                      55
##   WALL-E                  35
##                      
##                       male
##   A Bug&#39;s Life           6
##   Brave                 11
##   Cars                   9
##   Cars 2                 5
##   Finding Nemo          85
##   Inside Out           154
##   Monsters University   48
##   Monsters, Inc.        28
##   Ratatouille            1
##   The Incredibles       28
##   Toy Story              9
##   Toy Story 2           14
##   Toy Story 3            6
##   Up                    59
##   WALL-E                27
##                      
##                       other
##   A Bug&#39;s Life            1
##   Brave                   3
##   Cars                    2
##   Cars 2                  0
##   Finding Nemo           10
##   Inside Out             11
##   Monsters University     3
##   Monsters, Inc.          2
##   Ratatouille             1
##   The Incredibles         4
##   Toy Story               1
##   Toy Story 2             1
##   Toy Story 3             0
##   Up                      4
##   WALL-E                  3</code></pre>
<p>Going one step further, we can see that both of our two non-binary pirates who chose Monsters Inc., both use cutlasses.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="index.html#cb70-1"></a><span class="kw">table</span>(dataset<span class="op">$</span>fav.pixar,dataset<span class="op">$</span>sex,dataset<span class="op">$</span>sword.type)</span></code></pre></div>
<pre><code>## , ,  = banana
## 
##                      
##                       female
##   A Bug&#39;s Life             0
##   Brave                    1
##   Cars                     0
##   Cars 2                   1
##   Finding Nemo             3
##   Inside Out               3
##   Monsters University      4
##   Monsters, Inc.           0
##   Ratatouille              0
##   The Incredibles          0
##   Toy Story                1
##   Toy Story 2              0
##   Toy Story 3              0
##   Up                       7
##   WALL-E                   1
##                      
##                       male
##   A Bug&#39;s Life           0
##   Brave                  1
##   Cars                   0
##   Cars 2                 0
##   Finding Nemo           2
##   Inside Out            10
##   Monsters University    4
##   Monsters, Inc.         3
##   Ratatouille            0
##   The Incredibles        0
##   Toy Story              1
##   Toy Story 2            0
##   Toy Story 3            0
##   Up                     1
##   WALL-E                 0
##                      
##                       other
##   A Bug&#39;s Life            0
##   Brave                   0
##   Cars                    0
##   Cars 2                  0
##   Finding Nemo            1
##   Inside Out              0
##   Monsters University     1
##   Monsters, Inc.          0
##   Ratatouille             0
##   The Incredibles         0
##   Toy Story               0
##   Toy Story 2             0
##   Toy Story 3             0
##   Up                      0
##   WALL-E                  1
## 
## , ,  = cutlass
## 
##                      
##                       female
##   A Bug&#39;s Life            20
##   Brave                    6
##   Cars                     9
##   Cars 2                   8
##   Finding Nemo            53
##   Inside Out             116
##   Monsters University     31
##   Monsters, Inc.          17
##   Ratatouille              1
##   The Incredibles         28
##   Toy Story                5
##   Toy Story 2              9
##   Toy Story 3              6
##   Up                      40
##   WALL-E                  30
##                      
##                       male
##   A Bug&#39;s Life           5
##   Brave                  8
##   Cars                   6
##   Cars 2                 4
##   Finding Nemo          72
##   Inside Out           131
##   Monsters University   41
##   Monsters, Inc.        23
##   Ratatouille            1
##   The Incredibles       23
##   Toy Story              6
##   Toy Story 2           14
##   Toy Story 3            5
##   Up                    54
##   WALL-E                21
##                      
##                       other
##   A Bug&#39;s Life            0
##   Brave                   3
##   Cars                    2
##   Cars 2                  0
##   Finding Nemo            9
##   Inside Out              9
##   Monsters University     2
##   Monsters, Inc.          2
##   Ratatouille             1
##   The Incredibles         3
##   Toy Story               1
##   Toy Story 2             1
##   Toy Story 3             0
##   Up                      3
##   WALL-E                  1
## 
## , ,  = sabre
## 
##                      
##                       female
##   A Bug&#39;s Life             0
##   Brave                    0
##   Cars                     0
##   Cars 2                   0
##   Finding Nemo             9
##   Inside Out               9
##   Monsters University      5
##   Monsters, Inc.           1
##   Ratatouille              0
##   The Incredibles          1
##   Toy Story                0
##   Toy Story 2              1
##   Toy Story 3              0
##   Up                       5
##   WALL-E                   0
##                      
##                       male
##   A Bug&#39;s Life           1
##   Brave                  0
##   Cars                   1
##   Cars 2                 1
##   Finding Nemo           7
##   Inside Out            10
##   Monsters University    2
##   Monsters, Inc.         1
##   Ratatouille            0
##   The Incredibles        2
##   Toy Story              2
##   Toy Story 2            0
##   Toy Story 3            1
##   Up                     1
##   WALL-E                 3
##                      
##                       other
##   A Bug&#39;s Life            0
##   Brave                   0
##   Cars                    0
##   Cars 2                  0
##   Finding Nemo            0
##   Inside Out              2
##   Monsters University     0
##   Monsters, Inc.          0
##   Ratatouille             0
##   The Incredibles         0
##   Toy Story               0
##   Toy Story 2             0
##   Toy Story 3             0
##   Up                      1
##   WALL-E                  1
## 
## , ,  = scimitar
## 
##                      
##                       female
##   A Bug&#39;s Life             1
##   Brave                    0
##   Cars                     1
##   Cars 2                   0
##   Finding Nemo             2
##   Inside Out              11
##   Monsters University      3
##   Monsters, Inc.           2
##   Ratatouille              0
##   The Incredibles          5
##   Toy Story                0
##   Toy Story 2              0
##   Toy Story 3              1
##   Up                       3
##   WALL-E                   4
##                      
##                       male
##   A Bug&#39;s Life           0
##   Brave                  2
##   Cars                   2
##   Cars 2                 0
##   Finding Nemo           4
##   Inside Out             3
##   Monsters University    1
##   Monsters, Inc.         1
##   Ratatouille            0
##   The Incredibles        3
##   Toy Story              0
##   Toy Story 2            0
##   Toy Story 3            0
##   Up                     3
##   WALL-E                 3
##                      
##                       other
##   A Bug&#39;s Life            1
##   Brave                   0
##   Cars                    0
##   Cars 2                  0
##   Finding Nemo            0
##   Inside Out              0
##   Monsters University     0
##   Monsters, Inc.          0
##   Ratatouille             0
##   The Incredibles         1
##   Toy Story               0
##   Toy Story 2             0
##   Toy Story 3             0
##   Up                      0
##   WALL-E                  0</code></pre>
</div>
<div id="S.Tutorial.2C.7" class="section level3">
<h3><span class="header-section-number">1.8.7</span> Basic plots (one variable)</h3>
<p>In general, there are two very good websites for making professional graphics in R. I regularly browse both of them along with stack overflow to generate plots to be proud of, or to ask questions like “how do I change the axis size?”.</p>
<ul>
<li>Stat-Methods
<ul>
<li><a href="https://www.statmethods.net/graphs/index.html" class="uri">https://www.statmethods.net/graphs/index.html</a></li>
<li><a href="https://www.statmethods.net/advgraphs/index.html" class="uri">https://www.statmethods.net/advgraphs/index.html</a></li>
</ul></li>
<li>R Graph gallery
<ul>
<li><a href="https://www.r-graph-gallery.com/index.html" class="uri">https://www.r-graph-gallery.com/index.html</a></li>
</ul></li>
</ul>
<div id="histograms" class="section level4 unnumbered">
<h4>Histograms</h4>
<p>We discussed the basic histogram command last week: <code>hist(variable)</code>. For example <code>hist(malepirates$age)</code> makes a histogram of the age column in the data.frame we created earlier on male pirates.</p>
<ul>
<li>To make it look prettier, have a look at ?hist - or this article: <a href="https://www.statmethods.net/graphs/density.html" class="uri">https://www.statmethods.net/graphs/density.html</a></li>
<li>Or.. you can make any one of these histograms using the ggplot package (<a href="https://www.r-graph-gallery.com/histogram.html" class="uri">https://www.r-graph-gallery.com/histogram.html</a>)</li>
</ul>
</div>
<div id="boxplots" class="section level4 unnumbered">
<h4>Boxplots</h4>
<p>We discussed the basic boxplot command last week: <code>boxplot(variable)</code>. For example <code>boxplot(malepirates$age)</code> makes a boxplot of the age column in the data.frame we created earlier on male pirates. To be more fancy:</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="index.html#cb72-1"></a><span class="kw">boxplot</span>(age<span class="op">~</span>sex,         </span>
<span id="cb72-2"><a href="index.html#cb72-2"></a>        <span class="dt">data=</span>dataset,                       </span>
<span id="cb72-3"><a href="index.html#cb72-3"></a>        <span class="dt">xlab=</span><span class="st">&quot;Gender&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Age&quot;</span>) </span>
<span id="cb72-4"><a href="index.html#cb72-4"></a>        <span class="co">#names=c(&quot;Male&quot;,&quot;Female&quot;,&quot;Non-binary&quot;))</span></span></code></pre></div>
<ul>
<li>To make it look prettier, have a look at ?boxplot - or this article: <a href="https://www.statmethods.net/graphs/boxplot.html" class="uri">https://www.statmethods.net/graphs/boxplot.html</a></li>
<li>Or.. you can make any one of these boxplots (<a href="https://www.r-graph-gallery.com/boxplot.html" class="uri">https://www.r-graph-gallery.com/boxplot.html</a>)</li>
</ul>
</div>
<div id="qq-norm-plots" class="section level4 unnumbered">
<h4>QQ-Norm plots</h4>
<p>We discussed the basic qqnorm command last week: <code>qqplot(variable)</code>. For example <code>qqplot(malepirates$age)</code> makes a qq-norm plot of the age column in the data.frame we created earlier on male pirates. There is a nicer version inside the ggpubr package.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="index.html#cb73-1"></a><span class="kw">library</span>(ggpubr)</span>
<span id="cb73-2"><a href="index.html#cb73-2"></a><span class="kw">ggqqplot</span>(malepirates<span class="op">$</span>age,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
</div>
</div>
</div>
<div id="S.Tutorial.2D" class="section level2">
<h2><span class="header-section-number">1.9</span> Tutorial 2D: Distributions and tests</h2>
<p>We have talked about several distributions and tests so far in the lab. To see the help files for most of them, see <code>?Distributions</code></p>
<div id="S.Tutorial.2D.1" class="section level3">
<h3><span class="header-section-number">1.9.1</span> Normal distribution</h3>
<p>To see the help file for all these:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="index.html#cb74-1"></a>?Normal</span></code></pre></div>
<p>To generate a random sample from a normal distribution:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="index.html#cb75-1"></a>sample.normal &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n=</span><span class="dv">100</span>,<span class="dt">mean=</span><span class="dv">4</span>,<span class="dt">sd=</span><span class="dv">2</span>)</span></code></pre></div>
<p>To calculate a z score from your sample/population, you can use R as a calculator.</p>
<p>To calculate the probability of greater/lesser than a value in a given normal distribution (e.g. you can use this as an interactive table)</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="index.html#cb76-1"></a><span class="co"># probability of less than 1.7 in a normal distribution of N(4,2^2)</span></span>
<span id="cb76-2"><a href="index.html#cb76-2"></a><span class="kw">pnorm</span>(<span class="fl">1.7</span>,<span class="dt">mean=</span><span class="dv">4</span>,<span class="dt">sd=</span><span class="dv">2</span>,<span class="dt">lower.tail =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 0.1250719</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="index.html#cb78-1"></a><span class="co"># probability of greater than 1.8 in a normal distribution of N(4,2^2)</span></span>
<span id="cb78-2"><a href="index.html#cb78-2"></a><span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="dv">1</span>,<span class="dt">mean=</span><span class="dv">4</span>,<span class="dt">sd=</span><span class="dv">2</span>,<span class="dt">lower.tail =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 0.9331928</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="index.html#cb80-1"></a><span class="co"># or</span></span>
<span id="cb80-2"><a href="index.html#cb80-2"></a><span class="kw">pnorm</span>(<span class="dv">1</span>,<span class="dt">mean=</span><span class="dv">4</span>,<span class="dt">sd=</span><span class="dv">2</span>,<span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.9331928</code></pre>
<p>To calculate the value for a given probability</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="index.html#cb82-1"></a><span class="co"># what value is less than 60% of the data?</span></span>
<span id="cb82-2"><a href="index.html#cb82-2"></a><span class="kw">qnorm</span>(<span class="fl">0.6</span>,<span class="dt">mean=</span><span class="dv">4</span>,<span class="dt">sd=</span><span class="dv">2</span>,<span class="dt">lower.tail =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 4.506694</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="index.html#cb84-1"></a><span class="co"># what value is greater than 80% of the data?</span></span>
<span id="cb84-2"><a href="index.html#cb84-2"></a><span class="kw">qnorm</span>(<span class="fl">0.8</span>,<span class="dt">mean=</span><span class="dv">4</span>,<span class="dt">sd=</span><span class="dv">2</span>,<span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 2.316758</code></pre>
</div>
<div id="S.Tutorial.2D.2" class="section level3">
<h3><span class="header-section-number">1.9.2</span> Student’s t-distribution</h3>
<p>What even is this? See this nice resource: <a href="https://365datascience.com/tutorials/statistics-tutorials/students-t-distribution/" class="uri">https://365datascience.com/tutorials/statistics-tutorials/students-t-distribution/</a></p>
<p>To see the help file for all these:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="index.html#cb86-1"></a>?TDist</span></code></pre></div>
<p>To calculate a t-statistic from your sample/population, you can use R as a calculator. To calculate the probability of greater/lesser than a value in a given t-distribution (e.f. you can use this as an interactive t-table)</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="index.html#cb87-1"></a><span class="co"># probability of seeing less than 1.7 in a  t-distribution </span></span>
<span id="cb87-2"><a href="index.html#cb87-2"></a><span class="co"># with 20 degrees of freedom</span></span>
<span id="cb87-3"><a href="index.html#cb87-3"></a><span class="kw">pt</span>(<span class="fl">1.55</span>,<span class="dt">df=</span><span class="dv">20</span>,<span class="dt">lower.tail =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 0.9315892</code></pre>
<p>To calculate the value for a given probability</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="index.html#cb89-1"></a><span class="co"># what value is greater than 90% of the data in a t-distribution with df=25</span></span>
<span id="cb89-2"><a href="index.html#cb89-2"></a><span class="kw">qt</span>(<span class="fl">0.9</span>,<span class="dt">df=</span><span class="dv">25</span>,<span class="dt">lower.tail =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 1.316345</code></pre>
<p>To conduct a full t-test on some data:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="index.html#cb91-1"></a><span class="co"># Conduct a one sided t-test where we think that H0: mu(age)=30 on our pirates data (e.g. H1: mu(age) != 30 )</span></span>
<span id="cb91-2"><a href="index.html#cb91-2"></a><span class="kw">t.test</span>(dataset<span class="op">$</span>age,<span class="dt">mu=</span><span class="dv">30</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
## 	One Sample t-test
## 
## data:  dataset$age
## t = -14.427, df = 999,
## p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 30
## 95 percent confidence interval:
##  27.00092 27.71908
## sample estimates:
## mean of x 
##     27.36</code></pre>
<p>or see the detailed tutorial here: <a href="http://www.sthda.com/english/wiki/one-sample-t-test-in-r" class="uri">http://www.sthda.com/english/wiki/one-sample-t-test-in-r</a> for one-sample</p>
<p>and here for comparing two samples: <a href="http://www.sthda.com/english/wiki/unpaired-two-samples-t-test-in-r" class="uri">http://www.sthda.com/english/wiki/unpaired-two-samples-t-test-in-r</a></p>
</div>
<div id="S.Tutorial.2D.3" class="section level3">
<h3><span class="header-section-number">1.9.3</span> Wilks Shapiro test for normality</h3>
<p>To test for normality:</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="index.html#cb93-1"></a><span class="co"># Conduct a W-S test for normality on the ages of pirates</span></span>
<span id="cb93-2"><a href="index.html#cb93-2"></a><span class="kw">shapiro.test</span>(dataset<span class="op">$</span>age)</span></code></pre></div>
<pre><code>## 
## 	Shapiro-Wilk normality
## 	test
## 
## data:  dataset$age
## W = 0.99617, p-value =
## 0.01456</code></pre>
</div>
</div>
<div id="S.Tutorial.3A" class="section level2">
<h2><span class="header-section-number">1.10</span> Tutorial 3A - Editing code chunks</h2>
<p>R code chunks are really useful as you can completely control the output seen in your final report. To edit these, we edit the bit INSIDE the curly brackets at the top of the code chunk.</p>
<p>For example,</p>
<div class="figure"><span id="fig:chunkoptions"></span>
<img src="images/Fig03_02ChunkOptions.png" alt="Replace option1, option2 etc with the things you want the chunk to do" width="792" />
<p class="caption">
Figure 1.15: Replace option1, option2 etc with the things you want the chunk to do
</p>
</div>
<p>There are a huge number of options available as described here: <a href="https://bookdown.org/yihui/rmarkdown-cookbook/chunk-options.html" class="uri">https://bookdown.org/yihui/rmarkdown-cookbook/chunk-options.html</a></p>
<p>For now, we will focus on some basics:</p>
<p><strong>Q: How can I stop all the friendly “loading library” text coming up when I load a library?</strong></p>
<p>Ans: we include message=FALSE and warnings=FALSE at the top of the code chunk e.g.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="index.html#cb95-1"></a><span class="kw">library</span>(<span class="st">&quot;yarrr&quot;</span>)</span></code></pre></div>
<p><strong>Q: How can I add a figure caption?</strong></p>
<p>Ans. Using the fig.cap argument e.g. ```{r,fig.cap=“my caption”}</p>
<p><strong>Q: How can I make the code invisible?</strong></p>
<p>Ans: Unless specifically asked, I don’t recommend doing this in STAT-462 because we are grading you on your ability to code! But it is a useful skill. Here is how to do it for a figure insert (the most common request). I also gave my code chunk a name (chipmunk.pic), so that I can refer to it later in the text.</p>
<p>For example, this code:</p>
<p><img src="images/Fig03_03Chipnunkcode.png" width="810" /></p>
<p>Will lead to this output (the caption only shows up when you knit)</p>
<div class="figure">
<img src="images/Fig03_04Chipmunk.png" alt="Summer!" width="950" />
<p class="caption">
(#fig:chipmunk.pic)Summer!
</p>
</div>
</div>
<div id="S.Tutorial.3B" class="section level2">
<h2><span class="header-section-number">1.11</span> Tutorial 3B - Regression Models</h2>
<p>Now we will fit our first regression model.</p>
<div id="S.Tutorial.3B.1" class="section level3">
<h3><span class="header-section-number">1.11.1</span> “Standard” regression output</h3>
<p>The command to do this is <code>lm()</code> e.g. linear model.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="index.html#cb96-1"></a>output &lt;-<span class="st"> </span><span class="kw">lm</span>(y_column <span class="op">~</span><span class="st"> </span>x_column,<span class="dt">data=</span>tablename)</span>
<span id="cb96-2"><a href="index.html#cb96-2"></a>output</span></code></pre></div>
<p>NOTE, THE WEIRD ~ SYMBOL. This means “depends on” and it’s how we tell R what the response variable is. E.g. y depends on x, or y=mx+c. </p>
<p>For example for the starwars data, it would be</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="index.html#cb97-1"></a><span class="co"># response = mass, predictor = height</span></span>
<span id="cb97-2"><a href="index.html#cb97-2"></a>star.lm &lt;-<span class="st"> </span><span class="kw">lm</span>(mass <span class="op">~</span><span class="st"> </span>height,<span class="dt">data=</span>starwars)</span>
<span id="cb97-3"><a href="index.html#cb97-3"></a>star.lm</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mass ~ height, data = starwars)
## 
## Coefficients:
## (Intercept)       height  
##    -13.8103       0.6386</code></pre>
<p>You can also look at the summary by looking at the summary command:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="index.html#cb99-1"></a><span class="kw">summary</span>(star.lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mass ~ height, data = starwars)
## 
## Residuals:
##     Min      1Q  Median 
##  -61.43  -30.03  -21.13 
##      3Q     Max 
##  -17.73 1260.06 
## 
## Coefficients:
##             Estimate
## (Intercept) -13.8103
## height        0.6386
##             Std. Error
## (Intercept)   111.1545
## height          0.6261
##             t value Pr(&gt;|t|)
## (Intercept)  -0.124    0.902
## height        1.020    0.312
## 
## Residual standard error: 169.4 on 57 degrees of freedom
##   (28 observations deleted due to missingness)
## Multiple R-squared:  0.01792,	Adjusted R-squared:  0.0006956 
## F-statistic:  1.04 on 1 and 57 DF,  p-value: 0.312</code></pre>
<p>In both cases, we have an estimate of the intercept (0.6386) and of the gradient (-13.8103). We will discuss the other values in later labs/lectures.</p>
<p>Now let’s see how to add the regression line to our scatterplot. We can do this using <code>abline(REGRESSION_VARIABLE)</code>, where regression_variable is the name of the variable you saved the output of lm to. For example.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="index.html#cb101-1"></a><span class="kw">plot</span>(starwars<span class="op">$</span>height,starwars<span class="op">$</span>mass)</span>
<span id="cb101-2"><a href="index.html#cb101-2"></a><span class="kw">abline</span>(star.lm)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
</div>
<div id="S.Tutorial.3B.2" class="section level3">
<h3><span class="header-section-number">1.11.2</span> “Fancy” OLSRR regression output</h3>
<p>If you want a different way of seeing the same output, you can use the <code>ols_regress()</code> command inside the <code>olsrr</code> package.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="index.html#cb102-1"></a><span class="kw">library</span>(olsrr)</span>
<span id="cb102-2"><a href="index.html#cb102-2"></a>star.ols.lm &lt;-<span class="st"> </span><span class="kw">ols_regress</span>(mass <span class="op">~</span><span class="st"> </span>height,<span class="dt">data=</span>starwars)</span>
<span id="cb102-3"><a href="index.html#cb102-3"></a>star.ols.lm</span></code></pre></div>
<pre><code>##                           Model Summary                            
## ------------------------------------------------------------------
## R                        0.134       RMSE                 166.502 
## R-Squared                0.018       Coef. Var            174.078 
## Adj. R-Squared           0.001       MSE                28695.756 
## Pred R-Squared          -0.017       MAE                   46.669 
## ------------------------------------------------------------------
##  RMSE: Root Mean Square Error 
##  MSE: Mean Square Error 
##  MAE: Mean Absolute Error 
## 
##                                 ANOVA                                  
## ----------------------------------------------------------------------
##                    Sum of                                             
##                   Squares        DF    Mean Square      F        Sig. 
## ----------------------------------------------------------------------
## Regression      29854.272         1      29854.272     1.04    0.3120 
## Residual      1635658.069        57      28695.756                    
## Total         1665512.342        58                                   
## ----------------------------------------------------------------------
## 
##                                     Parameter Estimates                                      
## --------------------------------------------------------------------------------------------
##       model       Beta    Std. Error    Std. Beta      t        Sig        lower      upper 
## --------------------------------------------------------------------------------------------
## (Intercept)    -13.810       111.155                 -0.124    0.902    -236.393    208.773 
##      height      0.639         0.626        0.134     1.020    0.312      -0.615      1.892 
## --------------------------------------------------------------------------------------------</code></pre>
<p>The ols_regress command produces beautiful output, but sometimes it doesn’t work well with other commands. So I tend to run a lm command at the same time to have both available.</p>
<p>Sometimes, this command can produce a weird error:</p>
<div class="figure">
<img src="images/Fig03_05OLSRR.png" alt="This is probably because you loaded the moderndive package" width="776" />
<p class="caption">
(#fig:olsrr.error)This is probably because you loaded the moderndive package
</p>
</div>
<p>This is probably because you loaded the moderndive package. They do not play nicely together. Save your work, restart R and <strong>do not run any line that says library(moderndive)!</strong>.</p>
</div>
</div>
<div id="S.Tutorial.4A" class="section level2">
<h2><span class="header-section-number">1.12</span> Tutorial 4A: Plotting in ggplot2</h2>
<p>There are <em>many</em> tutorials out there, so I don’t want to spam you with my additional instructions.</p>
<p>Here are my top resources for learning how to plot in ggplot2.</p>
<ol style="list-style-type: decimal">
<li>There is a data camp course on it! <a href="https://learn.datacamp.com/courses/introduction-to-data-visualization-with-ggplot2" class="uri">https://learn.datacamp.com/courses/introduction-to-data-visualization-with-ggplot2</a></li>
<li>Modifiable examples: <a href="https://www.r-graph-gallery.com" class="uri">https://www.r-graph-gallery.com</a></li>
<li>For basic plotting, I like this: <a href="http://www.sthda.com/english/wiki/ggplot2-scatter-plots-quick-start-guide-r-software-and-data-visualization" class="uri">http://www.sthda.com/english/wiki/ggplot2-scatter-plots-quick-start-guide-r-software-and-data-visualization</a></li>
<li>Another nice tutorial to work through: <a href="https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html" class="uri">https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html</a></li>
<li>More details: <a href="https://r4ds.had.co.nz/data-visualisation.html" class="uri">https://r4ds.had.co.nz/data-visualisation.html</a></li>
<li>Every detail you could ever want. I use this as a reference. <a href="https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/" class="uri">https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/</a></li>
</ol>
</div>
<div id="S.Tutorial.4B" class="section level2">
<h2><span class="header-section-number">1.13</span> Tutorial 4B: Identifying/removing outliers</h2>
<p>Note this tutorial is not about whether you SHOULD remove an outlier or any other value, it’s simply about the mechanics of how to do so if you choose.</p>
<p>OK, let’s make a test dataset. I can do this using the data.frame() command.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="index.html#cb104-1"></a>test &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">VarA=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">3</span><span class="op">:</span><span class="dv">7</span>,<span class="dv">2</span>,<span class="dv">6</span>,<span class="dv">2</span>,<span class="dv">10</span>),<span class="dt">VarB=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">3</span><span class="op">:</span><span class="dv">7</span>,<span class="dv">5</span>,<span class="dv">2</span>,<span class="dv">5</span>,<span class="op">-</span><span class="dv">30</span>))</span>
<span id="cb104-2"><a href="index.html#cb104-2"></a>test</span></code></pre></div>
<pre><code>##    VarA VarB
## 1     2    1
## 2     5    4
## 3     3    3
## 4     4    4
## 5     5    5
## 6     6    6
## 7     7    7
## 8     2    5
## 9     6    2
## 10    2    5
## 11   10  -30</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="index.html#cb106-1"></a><span class="kw">plot</span>(test<span class="op">$</span>VarA,test<span class="op">$</span>VarB,<span class="dt">pch=</span><span class="dv">16</span>)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<p>There is a point that looks very suspicious and we want to identify it.</p>
<div id="method-1filter" class="section level5 unnumbered">
<h5>Method 1:Filter</h5>
<p>We can look at the plot, then use the filter command to identify it and print it out onto the screen.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="index.html#cb107-1"></a><span class="kw">filter</span>(test,VarB <span class="op">&lt;</span><span class="st"> </span><span class="dv">-20</span> <span class="op">&amp;</span><span class="st"> </span>VarA <span class="op">&gt;</span><span class="dv">9</span>)</span></code></pre></div>
<pre><code>##   VarA VarB
## 1   10  -30</code></pre>
<p>or similarly:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="index.html#cb109-1"></a><span class="co"># This version shows the row number</span></span>
<span id="cb109-2"><a href="index.html#cb109-2"></a>test[(test<span class="op">$</span>VarB <span class="op">&lt;</span><span class="st"> </span><span class="dv">-20</span>)<span class="op">&amp;</span>(test<span class="op">$</span>VarA <span class="op">&gt;</span><span class="dv">9</span>),]</span></code></pre></div>
<pre><code>##    VarA VarB
## 11   10  -30</code></pre>
<p>We can check the outlier by recoloring it on our plot using the <code>lines()</code> command: (NOTE YOU NEED BOTH PLOT AND LINES IN THE SAME CODE CHUNK FOR THIS TO WORK)</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="index.html#cb111-1"></a>outlier &lt;-<span class="st"> </span><span class="kw">filter</span>(test,VarB <span class="op">&lt;</span><span class="st"> </span><span class="dv">-20</span> <span class="op">&amp;</span><span class="st"> </span>VarA <span class="op">&gt;</span><span class="dv">9</span>)</span>
<span id="cb111-2"><a href="index.html#cb111-2"></a></span>
<span id="cb111-3"><a href="index.html#cb111-3"></a><span class="co"># Make the initial plot</span></span>
<span id="cb111-4"><a href="index.html#cb111-4"></a><span class="co"># Add the outlier as type=&quot;p&quot; for points.</span></span>
<span id="cb111-5"><a href="index.html#cb111-5"></a><span class="kw">plot</span>(test<span class="op">$</span>VarA,test<span class="op">$</span>VarB, <span class="dt">pch=</span><span class="dv">16</span>)</span>
<span id="cb111-6"><a href="index.html#cb111-6"></a><span class="kw">lines</span>(outlier<span class="op">$</span>VarA,outlier<span class="op">$</span>VarB,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">type=</span><span class="st">&quot;p&quot;</span>,<span class="dt">pch=</span><span class="dv">16</span>)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
<p>To remove it, we simply use filter the other way, e.g. use it to select everything else..</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="index.html#cb112-1"></a>newtest &lt;-<span class="st"> </span><span class="kw">filter</span>(test,VarB <span class="op">&gt;</span><span class="st"> </span><span class="dv">-20</span>)</span>
<span id="cb112-2"><a href="index.html#cb112-2"></a><span class="kw">plot</span>(newtest<span class="op">$</span>VarA,newtest<span class="op">$</span>VarB,<span class="dt">pch=</span><span class="dv">16</span>)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
</div>
<div id="method-2-identify-command" class="section level5 unnumbered">
<h5>Method 2: Identify Command</h5>
<p>Although R is mostly not interactive, there is one interactive tool you can use to click on a point and identify it, the <code>identify()</code> command.</p>
<p>THIS ONLY WORKS IN THE CONSOLE, DON’T RUN IN A CODE CHUNK</p>
<ol style="list-style-type: decimal">
<li><p>First, make sure that you can clearly see the plot quadrant of your screen (between Files &amp; Packages).</p></li>
<li><p>In the console, plot the data e.g. run <code>plot(test$VarA,test$VarB)</code>. You should see the plot clearly</p></li>
<li><p>Now, in the console, type <code>identify(test$VarA,test$VarB)</code>. When you press enter, your mouse will turn into a little cross. Click on all the points you want to identify THEN PRESS ESCAPE. The row number of the points you clicked on will appear in the plot</p></li>
</ol>
<p><img src="images/Fig04_01Identify.png" width="580" /></p>
<p>So now we know it is row 11 that is causing the problem. We can take a look at it by typing</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="index.html#cb113-1"></a><span class="co"># E.g. JUST row 11 and all the columns</span></span>
<span id="cb113-2"><a href="index.html#cb113-2"></a>test[<span class="dv">11</span>, ]</span></code></pre></div>
<pre><code>##    VarA VarB
## 11   10  -30</code></pre>
<p>and we can remove it with the minus sign</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="index.html#cb115-1"></a>newtest &lt;-<span class="st"> </span>test[<span class="op">-</span><span class="dv">11</span>, ]</span>
<span id="cb115-2"><a href="index.html#cb115-2"></a><span class="kw">plot</span>(newtest<span class="op">$</span>VarA,newtest<span class="op">$</span>VarB,<span class="dt">pch=</span><span class="dv">16</span>)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-67-1.png" width="672" /></p>
<p>Remember that if you do this more than once, all the row numbers will move around, so I am a fan of using identify to take a look at the data, but using filter to remove it.</p>
</div>
</div>
<div id="S.Tutorial.4C" class="section level2">
<h2><span class="header-section-number">1.14</span> Tutorial 4C Writing equations in R-Studio</h2>
<div id="S.Tutorial.4C.1" class="section level3">
<h3><span class="header-section-number">1.14.1</span> In Markdown</h3>
<div id="double-dollar-signs" class="section level5 unnumbered">
<h5>Double dollar signs</h5>
<p>It is relatively easy to write equations in R markdown. They use the “LaTeX” format and you put them between double dollar signs.</p>
<p>For example, try typing <code>$$x=2$$</code> on a new line of the white text area in your script ( NOT INTO A CODE CHUNK), then pressing knit. You should see:</p>
<p><span class="math display">\[x=2\]</span></p>
<p>But how do you write all the fancy equation stuff? We cheat.</p>
<p>Create the equation you want in one of these generators, then copy the code into your script and put it between double dollar signs:</p>
<ul>
<li><a href="https://latex.codecogs.com/eqneditor/editor.php" class="uri">https://latex.codecogs.com/eqneditor/editor.php</a></li>
<li><a href="https://www.tutorialspoint.com/latex_equation_editor.htm" class="uri">https://www.tutorialspoint.com/latex_equation_editor.htm</a></li>
</ul>
<p>For example</p>
<p><code>$$\widehat{y} = b_{0}+b_{1}x$$</code></p>
<p>Shows up as <span class="math display">\[\widehat{y} = b_{0}+b_{1}x\]</span></p>
<div id="single-dollar-signs" class="section level6 unnumbered">
<h6>Single dollar signs</h6>
<p>Essentially this is the same, but the equation is part of the text and you only see the output when you press knit. For example including <code>$x=2$</code> in this sentence shows <span class="math inline">\(x=2\)</span> as an output.</p>
</div>
</div>
</div>
<div id="S.Tutorial.4C.2" class="section level3">
<h3><span class="header-section-number">1.14.2</span> Using Equatiomatic</h3>
<p>There is a really neat package called <code>equatiomatic</code> that we can use to directly make equations from our linear models.</p>
<p>Tutorial here: <a href="https://cran.r-project.org/web/packages/equatiomatic/vignettes/intro-equatiomatic.html" class="uri">https://cran.r-project.org/web/packages/equatiomatic/vignettes/intro-equatiomatic.html</a></p>
<p>Install this package (e.g. using <code>install.packages("equatiomatic")</code>) and load it by putting <code>library(equatiomatic)</code> inside your “libraries” code chunk and re-running.</p>
<p>We can now extract an equation from any linear model variable. For example,</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="index.html#cb116-1"></a><span class="kw">data</span>(starwars)</span>
<span id="cb116-2"><a href="index.html#cb116-2"></a>mymodel &lt;-<span class="st"> </span><span class="kw">lm</span>(mass<span class="op">~</span>height,<span class="dt">data=</span>starwars)</span>
<span id="cb116-3"><a href="index.html#cb116-3"></a><span class="kw">extract_eq</span>(mymodel)</span></code></pre></div>
<p><span class="math display">\[
\operatorname{mass} = \alpha + \beta_{1}(\operatorname{height}) + \epsilon
\]</span></p>
<p>If you run it in the console, the command returns the LaTeX code you need to add it into the text yourself.</p>
<p>Let’s say our data is a sample, not the population, then we want to use lower case names for our sample statistics (b0 &amp; b1). There is no easy way to do this in the command, so I literally run the command in the console, then copy the command over to the TEXT part of the report and change the betas to ’b’s</p>
<p>If you want to use the actual numbers, simply turn on use_coefs=TRUE.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="index.html#cb117-1"></a><span class="kw">extract_eq</span>(mymodel, <span class="dt">use_coefs =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><span class="math display">\[
\operatorname{\widehat{mass}} = -13.81 + 0.64(\operatorname{height})
\]</span></p>
<p>Finally, you probably don’t want the code chunk showing up, so you can use the “echo=FALSE” argument inside the {r} part to stop the code chunk from being visible (see Tutorial 3A). For example, I ran exactly the same code chunk with echo=FALSE activated and got this:</p>
<p><span class="math display">\[
\operatorname{\widehat{mass}} = -13.81 + 0.64(\operatorname{height})
\]</span></p>
</div>
</div>
<div id="S.Tutorial.5A" class="section level2">
<h2><span class="header-section-number">1.15</span> Tutorial 5A ANOVA</h2>
<p>There are two quick and easy ways to make an ANOVA table. Lecture 13 describes it in a lot more detail.</p>
<div id="S.Tutorial.5A.1" class="section level3">
<h3><span class="header-section-number">1.15.1</span> Base R</h3>
<p>Simply use the ANOVA command. For example</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="index.html#cb118-1"></a><span class="kw">data</span>(starwars)</span>
<span id="cb118-2"><a href="index.html#cb118-2"></a>mymodel &lt;-<span class="st"> </span><span class="kw">lm</span>(mass<span class="op">~</span>height,<span class="dt">data=</span>starwars)</span>
<span id="cb118-3"><a href="index.html#cb118-3"></a><span class="kw">summary</span>(mymodel)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mass ~ height, data = starwars)
## 
## Residuals:
##     Min      1Q  Median 
##  -61.43  -30.03  -21.13 
##      3Q     Max 
##  -17.73 1260.06 
## 
## Coefficients:
##             Estimate
## (Intercept) -13.8103
## height        0.6386
##             Std. Error
## (Intercept)   111.1545
## height          0.6261
##             t value Pr(&gt;|t|)
## (Intercept)  -0.124    0.902
## height        1.020    0.312
## 
## Residual standard error: 169.4 on 57 degrees of freedom
##   (28 observations deleted due to missingness)
## Multiple R-squared:  0.01792,	Adjusted R-squared:  0.0006956 
## F-statistic:  1.04 on 1 and 57 DF,  p-value: 0.312</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="index.html#cb120-1"></a><span class="kw">anova</span>(mymodel)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: mass
##           Df  Sum Sq Mean Sq
## height     1   29854   29854
## Residuals 57 1635658   28696
##           F value Pr(&gt;F)
## height     1.0404  0.312
## Residuals</code></pre>
</div>
<div id="S.Tutorial.5A.2" class="section level3">
<h3><span class="header-section-number">1.15.2</span> Using OLSRR</h3>
<p>In OLSRR, it’s even easier. Our standard <code>ols_regress()</code> command includes ANOVA.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="index.html#cb122-1"></a><span class="kw">data</span>(starwars)</span>
<span id="cb122-2"><a href="index.html#cb122-2"></a>mymodel &lt;-<span class="st"> </span><span class="kw">lm</span>(mass<span class="op">~</span>height,<span class="dt">data=</span>starwars)</span>
<span id="cb122-3"><a href="index.html#cb122-3"></a><span class="kw">ols_regress</span>(mymodel)</span></code></pre></div>
<pre><code>##                           Model Summary                            
## ------------------------------------------------------------------
## R                        0.134       RMSE                 166.502 
## R-Squared                0.018       Coef. Var            174.078 
## Adj. R-Squared           0.001       MSE                28695.756 
## Pred R-Squared          -0.017       MAE                   46.669 
## ------------------------------------------------------------------
##  RMSE: Root Mean Square Error 
##  MSE: Mean Square Error 
##  MAE: Mean Absolute Error 
## 
##                                 ANOVA                                  
## ----------------------------------------------------------------------
##                    Sum of                                             
##                   Squares        DF    Mean Square      F        Sig. 
## ----------------------------------------------------------------------
## Regression      29854.272         1      29854.272     1.04    0.3120 
## Residual      1635658.069        57      28695.756                    
## Total         1665512.342        58                                   
## ----------------------------------------------------------------------
## 
##                                     Parameter Estimates                                      
## --------------------------------------------------------------------------------------------
##       model       Beta    Std. Error    Std. Beta      t        Sig        lower      upper 
## --------------------------------------------------------------------------------------------
## (Intercept)    -13.810       111.155                 -0.124    0.902    -236.393    208.773 
##      height      0.639         0.626        0.134     1.020    0.312      -0.615      1.892 
## --------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
<div id="S.Tutorial.5B" class="section level2">
<h2><span class="header-section-number">1.16</span> Tutorial 5B Diagnostics part A</h2>
<p>We know from the lectures that there are multiple assumptions underpinning whether a regression is a good model or not.These are described in detail in:</p>
<ul>
<li>Online STAT-462 - Lesson 4 (<a href="https://online.stat.psu.edu/stat462/node/116/" class="uri">https://online.stat.psu.edu/stat462/node/116/</a>)</li>
</ul>
<p>Regression diagnostics are a set of tools we can use to assess these assumptions. Many regression diagnostics include plots of standardized residuals, which we will focus on today.</p>
<p>Let’s use the example from the online textbook. Some researchers (Urbano-Marquez, et al., 1989) were interested in determining whether or not alcohol consumption was linearly related to muscle strength. The researchers measured the total lifetime consumption of alcohol (x) on a random sample of n = 50 alcoholic men. They also measured the strength (y) of the deltoid muscle in each person’s nondominant arm.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="index.html#cb124-1"></a>testdata &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;alcoholstrength.csv&quot;</span>)</span>
<span id="cb124-2"><a href="index.html#cb124-2"></a>mymodel &lt;-<span class="st"> </span><span class="kw">lm</span>(strength<span class="op">~</span>alcohol,<span class="dt">data=</span>testdata)</span>
<span id="cb124-3"><a href="index.html#cb124-3"></a><span class="kw">plot</span>(testdata<span class="op">$</span>alcohol,testdata<span class="op">$</span>strength,<span class="dt">xlab=</span><span class="st">&quot;Alcohol&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Strength&quot;</span>,<span class="dt">pch=</span><span class="dv">16</span>)</span>
<span id="cb124-4"><a href="index.html#cb124-4"></a><span class="kw">abline</span>(mymodel)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<div id="S.Tutorial.5B.1" class="section level3">
<h3><span class="header-section-number">1.16.1</span> Residual plots</h3>
<p>It can be difficult looking at the raw data to assess whether many of the assumptions are true or not. So in this case we can look at the residuals</p>
<p>We can access the residuals and many other model elements directly from the model</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="index.html#cb125-1"></a><span class="kw">names</span>(mymodel)</span></code></pre></div>
<pre><code>##  [1] &quot;coefficients&quot; 
##  [2] &quot;residuals&quot;    
##  [3] &quot;effects&quot;      
##  [4] &quot;rank&quot;         
##  [5] &quot;fitted.values&quot;
##  [6] &quot;assign&quot;       
##  [7] &quot;qr&quot;           
##  [8] &quot;df.residual&quot;  
##  [9] &quot;xlevels&quot;      
## [10] &quot;call&quot;         
## [11] &quot;terms&quot;        
## [12] &quot;model&quot;</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="index.html#cb127-1"></a><span class="co"># see ?lm for more explanation</span></span></code></pre></div>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="index.html#cb128-1"></a>testdata<span class="op">$</span>strength_predicted &lt;-<span class="st"> </span>mymodel<span class="op">$</span>fitted.values</span>
<span id="cb128-2"><a href="index.html#cb128-2"></a>testdata<span class="op">$</span>residuals          &lt;-<span class="st"> </span>mymodel<span class="op">$</span>residuals</span>
<span id="cb128-3"><a href="index.html#cb128-3"></a><span class="kw">head</span>(testdata)</span></code></pre></div>
<pre><code>##   alcohol strength
## 1    36.2     1000
## 2    39.7     1000
## 3    39.5     1080
## 4    18.2     1220
## 5    29.2     1310
## 6    32.5     1400
##   strength_predicted
## 1           1565.911
## 2           1462.357
## 3           1468.274
## 4           2098.474
## 5           1773.019
## 6           1675.382
##   residuals
## 1 -565.9109
## 2 -462.3570
## 3 -388.2744
## 4 -878.4739
## 5 -463.0187
## 6 -275.3822</code></pre>
<div id="residuals-vs-fitted-values" class="section level4 unnumbered">
<h4>Residuals vs fitted values</h4>
<p>The most common residual plot you will see is residuals vs predicted values for each point. You can see how to interpret it here: <a href="https://online.stat.psu.edu/stat462/node/117/" class="uri">https://online.stat.psu.edu/stat462/node/117/</a></p>
<p>Manually this is:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="index.html#cb130-1"></a><span class="kw">plot</span>(testdata<span class="op">$</span>strength_predicted,testdata<span class="op">$</span>residuals)</span>
<span id="cb130-2"><a href="index.html#cb130-2"></a><span class="kw">abline</span>(<span class="dt">h=</span><span class="dv">0</span>) <span class="co">#plot a horizontal line</span></span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-77-1.png" width="672" /></p>
<p>However R has many built in functions for this one:</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="index.html#cb131-1"></a><span class="co"># using the olsrr package</span></span>
<span id="cb131-2"><a href="index.html#cb131-2"></a><span class="kw">ols_plot_resid_fit</span>(mymodel)</span></code></pre></div>
<div class="figure"><span id="fig:resplot"></span>
<img src="Stat462_files/figure-html/resplot-1.png" alt="A residual plot for data that likely passes all the tests for linear regression" width="672" />
<p class="caption">
Figure 1.16: A residual plot for data that likely passes all the tests for linear regression
</p>
</div>
<p>We want our residuals to be normally distributed, random (e.g. independent) and showing no pattern or unequal variance.</p>
</div>
<div id="residuals-vs-predictor" class="section level4 unnumbered">
<h4>Residuals vs predictor</h4>
<p>Alternatively, we can use this to manually make a plot of the residuals against the x-values (the predictor) - see here for how to interpret this and compare it to the fitted value plot <a href="https://online.stat.psu.edu/stat462/node/118/" class="uri">https://online.stat.psu.edu/stat462/node/118/</a></p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="index.html#cb132-1"></a><span class="kw">plot</span>(testdata<span class="op">$</span>alcohol,testdata<span class="op">$</span>residuals)</span>
<span id="cb132-2"><a href="index.html#cb132-2"></a><span class="kw">abline</span>(<span class="dt">h=</span><span class="dv">0</span>) <span class="co">#plot a horizontal line</span></span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-78-1.png" width="672" /></p>
<p>Let’s use these to see how we can test the four assumptions underpinning linear regression (LINE).</p>
<p>Further residual interpretation can be seen here: <a href="https://online.stat.psu.edu/stat462/node/124/" class="uri">https://online.stat.psu.edu/stat462/node/124/</a></p>
</div>
</div>
<div id="S.Tutorial.5B.2" class="section level3">
<h3><span class="header-section-number">1.16.2</span> Checking Linearity</h3>
<p>If you are applying a linear model to data which is non-linear, you are in all sorts of trouble. Your model is simply a bad model and you will need some sort of transformation, or simply a better model altogether.</p>
<div class="figure"><span id="fig:unnamed-chunk-79"></span>
<img src="Stat462_files/figure-html/unnamed-chunk-79-1.png" alt="Don't be the person who makes this linear model!" width="672" />
<p class="caption">
Figure 1.17: Don’t be the person who makes this linear model!
</p>
</div>
<p>ALWAYS PLOT YOUR DATA AND LOOK AT IT (even if I don’t tell you to explicitly). For more examples of why this is useful to do, see here: <a href="https://online.stat.psu.edu/stat462/node/123/" class="uri">https://online.stat.psu.edu/stat462/node/123/</a></p>
<p>However, in real life, it can often be difficult to assess whether the fit is linear by looking at the scatterplot alone. So instead, we look at the residuals, whcih often show a pattern much more clearly. For example</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="index.html#cb133-1"></a>treadwear &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;treadwear.csv&quot;</span>)</span>
<span id="cb133-2"><a href="index.html#cb133-2"></a>tread_model &lt;-<span class="st"> </span><span class="kw">lm</span>(mileage<span class="op">~</span>groove,<span class="dt">data=</span>treadwear)</span>
<span id="cb133-3"><a href="index.html#cb133-3"></a><span class="kw">plot</span>(treadwear<span class="op">$</span>groove,treadwear<span class="op">$</span>mileage,<span class="dt">xlab=</span><span class="st">&quot;groove&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;mileage&quot;</span>,<span class="dt">pch=</span><span class="dv">16</span>)</span>
<span id="cb133-4"><a href="index.html#cb133-4"></a><span class="kw">abline</span>(tread_model)</span></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-80"></span>
<img src="Stat462_files/figure-html/unnamed-chunk-80-1.png" alt="This looks relatively linear, but...." width="672" />
<p class="caption">
Figure 1.18: This looks relatively linear, but….
</p>
</div>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="index.html#cb134-1"></a><span class="co"># using the olsrr package</span></span>
<span id="cb134-2"><a href="index.html#cb134-2"></a><span class="kw">ols_plot_resid_fit</span>(tread_model)</span></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-81"></span>
<img src="Stat462_files/figure-html/unnamed-chunk-81-1.png" alt="A parabola would clearly fit the data better" width="672" />
<p class="caption">
Figure 1.19: A parabola would clearly fit the data better
</p>
</div>
<p>Compare this residual plot to the strength/alcohol example above in Figure <a href="index.html#fig:resplot">1.16</a>. You can see in the treadwear data, the residuals depart from 0 in a very systematic manner. They are clearly positive for small x values, negative for medium x values, and positive again for large x values. Clearly, a non-linear model would better describe the relationship between the two variables. In future classes we will touch upon polynomial models that you might use to deal with this.</p>
</div>
<div id="S.Tutorial.5B.3" class="section level3">
<h3><span class="header-section-number">1.16.3</span> Checking Independence</h3>
<p>This is a tough one. Essentially we are asking if each row in our table is independent and representative of the population. So essentially we are looking for confounding variables. Or to put it another way, is there another variable that we need to include in our model.</p>
<p>Let’s say our data is not independent but we notice. What happens? First off, this isn’t so terrible as whether linearity is broken. The linear relationship likely still stands between our predictor and our response variable. So for example, there really is a relationship between height and weight that’s relatively linear. Or house prices in our State College pre-regressinon example might really be taken from a normal distribution.</p>
<p>BUT, it we had taken into account this new variable ALSO, we might have done an even better job. So for example, the relationship between height and weight is definitely affected by someone’s gender. Or in the example from Lab 3, knowing how close a house is to “downtown” is a better predictor of price than knowing how far East/West it is.</p>
<p>Equally, the non independence of our data makes it hard for us to be sure how good our model is or for us to make predictions. For example, if we were looking at height and weight and our sample was made up only of people who identified as women, then there might be clear limitations in predicting the weight of the men’s basketball team.</p>
<p>Because every case is different, there is no “set method” for checking independence, but there are a few common ways to check things that you are suspicious of. So the first item is to think about the problem. What might impact your response variable that you have not taken into account.</p>
<div id="covariance-matrix" class="section level4 unnumbered">
<h4>Covariance matrix</h4>
<p>Looking at correlations is a quick (but often misleading) way to assess what is happening. Essentially we can look at the correlation between each column of data.</p>
<p>The basic way to do this is very quick and easy. For example, let’s look at our Star Wars height/data.</p>
<p>The GGally function allows us to see the histogram of each column we choose to plot - along with the correlation of any numeric pairs. Let’s look at this for a new dataset looking at how much people are tipped in New York restaurants.</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="index.html#cb135-1"></a><span class="co"># Quick display of two capabilities of GGally, to assess the distribution and correlation of variables </span></span>
<span id="cb135-2"><a href="index.html#cb135-2"></a>house &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;Lab03_house.xlsx&quot;</span>)</span>
<span id="cb135-3"><a href="index.html#cb135-3"></a></span>
<span id="cb135-4"><a href="index.html#cb135-4"></a><span class="co"># Choose column names - let&#39;s say I don&#39;t care about location</span></span>
<span id="cb135-5"><a href="index.html#cb135-5"></a><span class="kw">colnames</span>(house)</span></code></pre></div>
<pre><code>## [1] &quot;House.Price&quot;     
## [2] &quot;House.Age&quot;       
## [3] &quot;Distance.Station&quot;
## [4] &quot;Number.Shops&quot;    
## [5] &quot;Latitude&quot;        
## [6] &quot;Longitude&quot;</code></pre>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="index.html#cb137-1"></a><span class="co"># Create plot - note I have message=TRUE and warning=TRUE turned on at the top of my code chunk</span></span>
<span id="cb137-2"><a href="index.html#cb137-2"></a><span class="kw">ggpairs</span>(house[,<span class="kw">c</span>(<span class="st">&quot;House.Price&quot;</span> ,<span class="st">&quot;House.Age&quot;</span>,<span class="st">&quot;Distance.Station&quot;</span>,<span class="st">&quot;Number.Shops&quot;</span> )])</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<p>You can simply look at the correlations of any NUMERIC columns using the corrplot code, as we did in Lab 3.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="index.html#cb138-1"></a><span class="kw">library</span>(corrplot)</span>
<span id="cb138-2"><a href="index.html#cb138-2"></a>house.subset &lt;-<span class="st"> </span>house[ , <span class="kw">sapply</span>(house,is.numeric)]</span>
<span id="cb138-3"><a href="index.html#cb138-3"></a><span class="kw">corrplot</span>(<span class="kw">cor</span>(house.subset),<span class="dt">method=</span><span class="st">&quot;ellipse&quot;</span>,<span class="dt">type=</span><span class="st">&quot;lower&quot;</span>)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p>There are LOADS of other ways to run correlation plots here: <a href="https://www.r-graph-gallery.com/correlogram.html" class="uri">https://www.r-graph-gallery.com/correlogram.html</a>
Feel free to choose a favourite.</p>
<p>Importantly, remember back to this website - <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. Just because another variable is correlated with our response does not mean it HAS to be in the model. It simply means that you might want to consider whether there is a reason for that correlation.</p>
</div>
<div id="scatterplots-and-residual-plots" class="section level4 unnumbered">
<h4>Scatterplots and residual plots</h4>
<p>A second way we looked at in a previous lab was to add colour to our scatterplot and see if we can see any influence.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="index.html#cb139-1"></a><span class="co"># Create a plot</span></span>
<span id="cb139-2"><a href="index.html#cb139-2"></a>p &lt;-<span class="st"> </span>house <span class="op">%&gt;%</span><span class="st">                  </span></span>
<span id="cb139-3"><a href="index.html#cb139-3"></a><span class="st">  </span><span class="kw">ggplot</span>( <span class="kw">aes</span>(Latitude,House.Price, <span class="dt">col=</span> Distance.Station)) <span class="op">+</span></span>
<span id="cb139-4"><a href="index.html#cb139-4"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb139-5"><a href="index.html#cb139-5"></a><span class="st">  </span><span class="kw">theme_classic</span>()<span class="op">+</span></span>
<span id="cb139-6"><a href="index.html#cb139-6"></a><span class="st">  </span><span class="kw">scale_color_gradient</span>(<span class="dt">low=</span><span class="st">&quot;blue&quot;</span>, <span class="dt">high=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb139-7"><a href="index.html#cb139-7"></a></span>
<span id="cb139-8"><a href="index.html#cb139-8"></a><span class="co"># and actually plot it</span></span>
<span id="cb139-9"><a href="index.html#cb139-9"></a><span class="kw">ggplotly</span>(p)</span></code></pre></div>
<p>However, this can be hard to see - so instead we can PLOT OUR RESIDUALS according to the variable we think is affecting independence. For example</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="index.html#cb140-1"></a>housemodel            &lt;-<span class="st"> </span><span class="kw">lm</span>(House.Price<span class="op">~</span>Latitude,<span class="dt">data=</span>house)</span>
<span id="cb140-2"><a href="index.html#cb140-2"></a>house<span class="op">$</span>price_predicted &lt;-<span class="st"> </span>housemodel<span class="op">$</span>fitted.values</span>
<span id="cb140-3"><a href="index.html#cb140-3"></a>house<span class="op">$</span>residuals       &lt;-<span class="st"> </span>housemodel<span class="op">$</span>residuals</span>
<span id="cb140-4"><a href="index.html#cb140-4"></a></span>
<span id="cb140-5"><a href="index.html#cb140-5"></a><span class="kw">plot</span>(house<span class="op">$</span>Distance.Station, house<span class="op">$</span>residuals)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-85-1.png" width="672" /></p>
<p>This definitely doesn’t look like a random cloud! It looks like distance to the station is really impacting the linear model between house price and latitude.</p>
<p>In this case we will use MULITPLE REGRESSION. (later in the course)</p>
</div>
<div id="if-your-data-includes-a-date-or-time-stamp" class="section level4 unnumbered">
<h4>If your data includes a date or time-stamp</h4>
<p>Then you have time-series data and there is an ENTIRE COURSE on modelling it (<a href="https://online.stat.psu.edu/stat510/" class="uri">https://online.stat.psu.edu/stat510/</a>). For now, if your data contains any time stamp or date, be very cautious. Changes are that your data contains auto-correlation e.g. the response tomorrow is likely to be affected by the response today.</p>
<p>In the short term, if you know the order in which your data was collected, you could plot a residuals/order plot as described here: <a href="https://online.stat.psu.edu/stat462/node/121/" class="uri">https://online.stat.psu.edu/stat462/node/121/</a>.</p>
</div>
<div id="if-your-data-includes-a-location" class="section level4 unnumbered">
<h4>If your data includes a location</h4>
<p>Spatial data is often not independent due to Tobler’s Law (close together things are more similar than those further apart). For example, imagine you were looking at the correlation between money spent on alcohol and undergraduate degree score Your relationship might be different in areas with lower drinking age-limits, or in countries where drinking is outlawed.</p>
<p>So knowing the location of your sample is important. The easiest thing we can do here to check for independence is to make a literal map of the residuals. For example, remember in lab 3 - let’s do something similar</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="index.html#cb141-1"></a><span class="co"># Command from the sf library</span></span>
<span id="cb141-2"><a href="index.html#cb141-2"></a><span class="co"># Make a spatial version of the data using the Longitide and Latitude columns</span></span>
<span id="cb141-3"><a href="index.html#cb141-3"></a>house.spatial &lt;-<span class="st"> </span><span class="kw">st_as_sf</span>(house,<span class="dt">coords=</span><span class="kw">c</span>(<span class="st">&quot;Longitude&quot;</span>,<span class="st">&quot;Latitude&quot;</span>),<span class="dt">crs =</span> <span class="dv">4326</span>)</span>
<span id="cb141-4"><a href="index.html#cb141-4"></a></span>
<span id="cb141-5"><a href="index.html#cb141-5"></a><span class="co"># make interactive, for static set as &quot;plot&quot;, for interactive set as &quot;view&quot;</span></span>
<span id="cb141-6"><a href="index.html#cb141-6"></a><span class="kw">tmap_mode</span>(<span class="st">&quot;plot&quot;</span>)</span>
<span id="cb141-7"><a href="index.html#cb141-7"></a></span>
<span id="cb141-8"><a href="index.html#cb141-8"></a><span class="co"># Command from the tmap library</span></span>
<span id="cb141-9"><a href="index.html#cb141-9"></a><span class="co"># and plot</span></span>
<span id="cb141-10"><a href="index.html#cb141-10"></a><span class="kw">qtm</span>(<span class="st">&quot;Esri.WorldTopoMap&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb141-11"><a href="index.html#cb141-11"></a><span class="st">     </span><span class="kw">qtm</span>(house.spatial, <span class="co"># data</span></span>
<span id="cb141-12"><a href="index.html#cb141-12"></a>         <span class="dt">symbols.col=</span><span class="st">&quot;residuals&quot;</span>, <span class="co"># which column for the symbols</span></span>
<span id="cb141-13"><a href="index.html#cb141-13"></a>         <span class="dt">symbols.size=</span>.<span class="dv">4</span>, <span class="co"># how big</span></span>
<span id="cb141-14"><a href="index.html#cb141-14"></a>         <span class="dt">symbols.palette=</span><span class="st">&quot;RdBu&quot;</span>,</span>
<span id="cb141-15"><a href="index.html#cb141-15"></a>         <span class="dt">midpoint=</span><span class="dv">0</span>) <span class="co"># color breaks</span></span></code></pre></div>
<p>There definitely LOOKS like the residuals are not randomly distributed in space, making me think there is spatial autocorrelation (e.g. correlation with itself - the location of a point impacts the residual).</p>
<p>We can test this through a statistic called Moran’s I - which plots the residual at each point against its residuals for surrounding points. In my spatial statistics course, we spend about 3 weeks just on this statistics, so there is a lot of nuance we are skipping over here. For more, see <a href="https://mgimond.github.io/Spatial/spatial-autocorrelation.html" class="uri">https://mgimond.github.io/Spatial/spatial-autocorrelation.html</a></p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="index.html#cb142-1"></a><span class="kw">library</span>(moranfast)</span>
<span id="cb142-2"><a href="index.html#cb142-2"></a><span class="kw">moranfast</span>(house<span class="op">$</span>residuals, </span>
<span id="cb142-3"><a href="index.html#cb142-3"></a>          house<span class="op">$</span>Longitude, </span>
<span id="cb142-4"><a href="index.html#cb142-4"></a>          house<span class="op">$</span>Latitude, </span>
<span id="cb142-5"><a href="index.html#cb142-5"></a>          <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## $observed
## [1] 0.1732675
## 
## $expected
## [1] -0.002421308
## 
## $sd
## [1] 0.02267439
## 
## $p.value
## [1] 9.325873e-15</code></pre>
<p>But essentially here we have a hypothesis test:</p>
<ul>
<li>H0: There is no spatial autocorrelation. The “colour”/value of each residual has complete spatial randomness. I = 0</li>
<li>H1: Spatial autocorrelation is present. There is a significant pattern in the “colour”/values of each point I != 0</li>
</ul>
<p>Test - The Global Moran’s I statistic is the correlation coefficient for the relationship between a variable (like income) and itself at surrounding values.</p>
<p>P-value - the probabiity of seeing this pattern if H0 really was true.</p>
<p>So here in this case, the p-value is very low, confirming what we visually see in the plot above. There is evidence to reject the null hypthesis and suggest that spatial autocorrelation is present.</p>
<p>If this is true, we can use spatial GLMs to take this into account (again, later in the course).</p>
</div>
</div>
<div id="S.Tutorial.5B.4" class="section level3">
<h3><span class="header-section-number">1.16.4</span> Checking Normality</h3>
<p>There are three things we might want to check around normality and regression - but essentially we are testing whether the RESIDUALS are normal around the regression line. To get the best estimates of parameters such as B0 and B1, the residuals must be normally distributed around the regression line. but this has a much smaller effect typically than non-linearity or breaking assumptions of independence.</p>
<p>Breaking normality is only important in the calculation of p values for significance testing and confidence intervals, but this is only a problem when the sample size is small. When the sample size is largeer (&gt;200), the Central Limit Theorem ensures that the distribution of residuals will approximate normality when calculating parameters.</p>
<p>So never throw away your data if it breaks normality. But it’s good to take a look.</p>
<p>Let’s go back to our original test data:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="index.html#cb144-1"></a>mymodel &lt;-<span class="st"> </span><span class="kw">lm</span>(strength<span class="op">~</span>alcohol,<span class="dt">data=</span>testdata)</span>
<span id="cb144-2"><a href="index.html#cb144-2"></a><span class="kw">plot</span>(testdata<span class="op">$</span>alcohol,testdata<span class="op">$</span>strength,<span class="dt">xlab=</span><span class="st">&quot;Alcohol&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Strength&quot;</span>,<span class="dt">pch=</span><span class="dv">16</span>)</span>
<span id="cb144-3"><a href="index.html#cb144-3"></a><span class="kw">abline</span>(mymodel)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-88-1.png" width="672" /></p>
<p>To test normality, we can use OLSRR to:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="index.html#cb145-1"></a><span class="co">#Create a QQ plot of the residuals</span></span>
<span id="cb145-2"><a href="index.html#cb145-2"></a><span class="kw">ols_plot_resid_qq</span>(mymodel)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-89-1.png" width="672" /></p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="index.html#cb146-1"></a><span class="co">#Create a histogram of the residuals</span></span>
<span id="cb146-2"><a href="index.html#cb146-2"></a><span class="kw">ols_plot_resid_hist</span>(mymodel)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-89-2.png" width="672" /></p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="index.html#cb147-1"></a><span class="co">#Run a Wilks-Shapiro test for normality</span></span>
<span id="cb147-2"><a href="index.html#cb147-2"></a><span class="kw">ols_test_normality</span>(mymodel)</span></code></pre></div>
<pre><code>## -----------------------------------------------
##        Test             Statistic       pvalue  
## -----------------------------------------------
## Shapiro-Wilk              0.9877         0.8767 
## Kolmogorov-Smirnov        0.0502         0.9990 
## Cramer-von Mises          4.1667         0.0000 
## Anderson-Darling          0.1699         0.9289 
## -----------------------------------------------</code></pre>
<p>In this case, our residuals look very normal.</p>
<p>Compare that to our house dataset, which suggests that the data is mildly non normal.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="index.html#cb149-1"></a>housemodel &lt;-<span class="st"> </span><span class="kw">lm</span>(House.Price<span class="op">~</span>Latitude,<span class="dt">data=</span>house)</span>
<span id="cb149-2"><a href="index.html#cb149-2"></a><span class="kw">plot</span>(house<span class="op">$</span>House.Price<span class="op">~</span>house<span class="op">$</span>Latitude,<span class="dt">xlab=</span><span class="st">&quot;Latitude&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;House Price&quot;</span>,<span class="dt">pch=</span><span class="dv">16</span>)</span>
<span id="cb149-3"><a href="index.html#cb149-3"></a><span class="kw">abline</span>(housemodel)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-90-1.png" width="672" /></p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="index.html#cb150-1"></a><span class="co">#Create a QQ plot of the residuals</span></span>
<span id="cb150-2"><a href="index.html#cb150-2"></a><span class="kw">ols_plot_resid_qq</span>(housemodel)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-90-2.png" width="672" /></p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="index.html#cb151-1"></a><span class="co">#Create a histogram of the residuals</span></span>
<span id="cb151-2"><a href="index.html#cb151-2"></a><span class="kw">ols_plot_resid_hist</span>(housemodel)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-90-3.png" width="672" /></p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="index.html#cb152-1"></a><span class="co">#Run a Wilks-Shapiro test for normality</span></span>
<span id="cb152-2"><a href="index.html#cb152-2"></a><span class="kw">ols_test_normality</span>(housemodel)</span></code></pre></div>
<pre><code>## Warning in ks.test(y, &quot;pnorm&quot;,
## mean(y), sd(y)): ties should
## not be present for the
## Kolmogorov-Smirnov test</code></pre>
<pre><code>## -----------------------------------------------
##        Test             Statistic       pvalue  
## -----------------------------------------------
## Shapiro-Wilk              0.9411         0.0000 
## Kolmogorov-Smirnov        0.0776         0.0138 
## Cramer-von Mises          34.21          0.0000 
## Anderson-Darling          4.3556         0.0000 
## -----------------------------------------------</code></pre>
<p>The answer to non-normal data is to use a GLM (Generalised Linear Model), which again we will get to later in the semester.</p>
<p>Alternatively you can use your linear model, but make the significance level more rigarous (say 1% rather than 5%) to take into account the fact that the assumptions underpinning the calculations might be flawed.</p>
<p>In terms of detailed interpretation, read this page: <a href="https://online.stat.psu.edu/stat462/node/122/" class="uri">https://online.stat.psu.edu/stat462/node/122/</a></p>
</div>
<div id="S.Tutorial.5B.5" class="section level3">
<h3><span class="header-section-number">1.16.5</span> Checking Equal Variance/homoskadisity</h3>
<p>The easiest thing to do here is to plot the residuals, then see if you see any variations in variance. For example in our house regression, the residuals look like this</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="index.html#cb155-1"></a><span class="kw">ols_plot_resid_fit</span>(housemodel)</span></code></pre></div>
<p><img src="Stat462_files/figure-html/unnamed-chunk-91-1.png" width="672" />
You can clearly see here that for low values of the fitted data, there is not much variance - but there is a lot of variance between 30-50</p>
<p>You can also run statistical tests, explained in more detail here: <a href="https://rpubs.com/tskam/Session06" class="uri">https://rpubs.com/tskam/Session06</a></p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="index.html#cb156-1"></a><span class="co"># F test - assumes residuals are  independent and identically distributed (i.i.d.)</span></span>
<span id="cb156-2"><a href="index.html#cb156-2"></a><span class="kw">ols_test_f</span>(housemodel)</span></code></pre></div>
<pre><code>## 
##  F Test for Heteroskedasticity
##  -----------------------------
##  Ho: Variance is homogenous
##  Ha: Variance is not homogenous
## 
##  Variables: fitted values of House.Price 
## 
##       Test Summary        
##  -------------------------
##  Num DF     =    1 
##  Den DF     =    412 
##  F          =    2.483727 
##  Prob &gt; F   =    0.1157969</code></pre>
<p>In this case, we can see that perhaps we neeed to worry less about unequal variance,</p>
<p>There is also another test available, the Breusch Pagan Test - but this relies on the residuals being normally distributed.</p>
</div>
</div>
<div id="S.Tutorial.5C" class="section level2">
<h2><span class="header-section-number">1.17</span> Tutorial 5C Confidence and Prediction Intervals</h2>
<p>Essentially these are two different things:</p>
<p><em>Confidence interval:</em> “Error bar” on the location of the regression line at any specific value of x, or “what is the uncertainty on the population mean of y, for a specific value of x?”</p>
<p>_Prediction interval:Predicting the range of likely y-values for a new data-point, or “if you had to put a new dot on the scatterplot, what range of y values would it fall under”</p>
<p>These are described in detail here:</p>
<ul>
<li><a href="https://online.stat.psu.edu/stat462/node/125/" class="uri">https://online.stat.psu.edu/stat462/node/125/</a></li>
<li><a href="https://online.stat.psu.edu/stat462/node/126/" class="uri">https://online.stat.psu.edu/stat462/node/126/</a></li>
<li><a href="https://online.stat.psu.edu/stat462/node/127/" class="uri">https://online.stat.psu.edu/stat462/node/127/</a></li>
<li><a href="https://online.stat.psu.edu/stat462/node/128/" class="uri">https://online.stat.psu.edu/stat462/node/128/</a></li>
</ul>
<p>In R:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="index.html#cb158-1"></a><span class="co">#For our pirate weight/height dataset</span></span>
<span id="cb158-2"><a href="index.html#cb158-2"></a>lm.pirate &lt;-<span class="st"> </span><span class="kw">lm</span>(weight<span class="op">~</span>height,<span class="dt">data=</span>pirates)</span>
<span id="cb158-3"><a href="index.html#cb158-3"></a><span class="kw">summary</span>(lm.pirate)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ height, data = pirates)
## 
## Residuals:
##      Min       1Q   Median 
## -12.3592  -2.6564  -0.0708 
##       3Q      Max 
##   2.7275  11.1451 
## 
## Coefficients:
##              Estimate
## (Intercept) -68.87722
## height        0.81434
##             Std. Error
## (Intercept)    1.71250
## height         0.01003
##             t value Pr(&gt;|t|)
## (Intercept)  -40.22   &lt;2e-16
## height        81.16   &lt;2e-16
##                
## (Intercept) ***
## height      ***
## ---
## Signif. codes:  
##   0 &#39;***&#39; 0.001 &#39;**&#39; 0.01
##   &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.928 on 998 degrees of freedom
## Multiple R-squared:  0.8684,	Adjusted R-squared:  0.8683 
## F-statistic:  6587 on 1 and 998 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="index.html#cb160-1"></a><span class="co"># What are the AVERAGE WEIGHTS (and uncertainty on our estimate) </span></span>
<span id="cb160-2"><a href="index.html#cb160-2"></a><span class="co"># of pirates whose heights are 150cm and 170cm?</span></span>
<span id="cb160-3"><a href="index.html#cb160-3"></a>new.pirates &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">height=</span><span class="kw">c</span>(<span class="dv">150</span>,<span class="dv">170</span>))</span>
<span id="cb160-4"><a href="index.html#cb160-4"></a><span class="kw">predict</span>(lm.pirate,<span class="dt">newdata=</span>new.pirates,<span class="dt">interval=</span><span class="st">&quot;confidence&quot;</span>,<span class="dt">level=</span><span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 53.27345 52.80652 53.74037
## 2 69.56020 69.31640 69.80400</code></pre>
<p>So we are 95% certain that on average, the AVERAGE weight of pirates who are 150cm tall falls between 52.8Kg and 53.74Kg</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="index.html#cb162-1"></a><span class="co"># A new pirate joins and her height is 160cm.  What range of weights is she likely to have?</span></span>
<span id="cb162-2"><a href="index.html#cb162-2"></a>new.pirates &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">height=</span><span class="kw">c</span>(<span class="dv">160</span>))</span>
<span id="cb162-3"><a href="index.html#cb162-3"></a><span class="kw">predict</span>(lm.pirate,<span class="dt">newdata=</span>new.pirates,<span class="dt">interval=</span><span class="st">&quot;predict&quot;</span>,<span class="dt">level=</span><span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 61.41682 53.70196 69.13169</code></pre>
<p>Her weight is likely to be somewhere between 53Kg and 69Kg with 95% certainty given our sample.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>

<a href="lab-1.html" class="navigation navigation-next navigation-unique" aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
